### ISSUE TITLE
Error : Cannot find module 'express'

### ISSUE THREAD

**Issue by babonet13** [ShahanaFarooqui/RTL#10]
I'm running bitcoind & LND on a machine named "naka-dev" with a user named "satoshi".
After RTL installation I go this error :

satoshi@naka-dev:/tmp/RTL$ node rtl --lndir /home/satoshi/.lnd/data/chain/bitcoin/mainnet
module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/RTL/app.js:2:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by saubyk** [comment]
@babonet13  Can you please confirm the below:
1. Whats your hardware configuration?
2. Was there any error message while/after running npm install?

Thanks.

**Comment by saubyk** [comment]
Didn’t hear back from you. Hoping your issue is resolved now.
Feel free to open another one, in case you are facing any problems. Thanks.

**Comment by babonet13** [comment]
Hi @Saubyk,
Sorry for the response delay (I was traveling very bad Internet connection)
My Hardware is a Intel NUC : https://www.intel.fr/content/www/fr/fr/products/boards-kits/nuc.html
My Software is Ubuntu

More detail here : 
satoshi@naka-dev:~$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
stepping        : 9
microcode       : 0x8e
cpu MHz         : 1655.857
cache size      : 4096 KB

Do not see other message while/after running npm

**Comment by saubyk** [comment]
@babonet13
This appears to be a npm dependency issue. Please check which version of npm you are running. If you are running an older version, upgrade npm first and then try the below.

Try `npm install express`
and see if that completes without any error.
If it does throw an error, you can explore more options on that...on the below stackoverflow thread...
https://stackoverflow.com/questions/12231846/npm-will-not-install-express

If express installation is successful you should be able to run the application. Do let us know.
Thanks.

**Comment by saubyk** [comment]
This appears to be an older version. I would recommend upgrading nodejs and npm.

**Comment by babonet13** [comment]
I have removed both nodejs and npm ...
... and the I have re-installed those packages 

I alway got the very same version : 
   - nodejs version = v8.11.4
   - npm version = 5.8.0

Is there a specific Ubuntu command for upgrading to a given version ?

**Comment by saubyk** [comment]
Hi @babonet13  curious if you are able to make any progress?
In case you are not,You can try the following:
`npm cache clear -f`
`npm cache verify`
and the change directory to RTL folder and run the below:
`npm install -f`

Let us know if this addresses the issue.

**Comment by babonet13** [comment]
I have try those comand.
After running "npm cache verify" it seems that I could upgrade from 5.8.0. to 6.4.1 ...
... but after passing the command "npm i npm" I always got the same version (5.8.0)

So nothing changed about the issue ...

I think I will wait to have the time to make the test on a brand new Ubuntu box ....

**Comment by saubyk** [comment]
Hi,
Wondering if you are still having issues with your Ubuntu setup.
If yes, you can look at the below issue for reference:
https://github.com/ShahanaFarooqui/RTL/issues/27#issue-397069524

Thanks.

**Comment by babonet13** [comment]
Hi, 
Too busy at this moment, I do not have the time to make a fresh brand new install of my node. I hope I colud come back is the LN game in few weeks ;-)
