### ISSUE TITLE
[Feature Request] - Add ability to handle multiple LND nodes via RTL

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#101]
RTL can be used to control multiple LND nodes via a single server instance.
The list of LND nodes with the config parameters will be maintained in a json file, which will be utilized by RTL, to connect to the nodes.

RTL will show the list of available nodes in the 'settings' menu. RTL will be default load the application with the first node in the list. User can access the settings menu and change the node to load into the application.

**Comment by ShahanaFarooqui** [comment]
Done with 0.3.0
