### ISSUE TITLE
[Feature Request] Regenerating fresh cookie and access key after use

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#103]
I noticed it is easy to shoot oneself in the foot by clicking on the link to go to RTL.

While we partially fixed the problem of the access_key showing in the browser history, a better way to completely fix the issue is to generate a brand new access_key once one has been use successfully.

The problem is that now the access key is showing on screen for short period of time, so somebody can easily leak his wallet by making a video or demo.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier Fixed and committed in master, will be released with v0.2.17. Thanks.
