### ISSUE TITLE
'Close Channel' icon not appearing clickable

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#106]
'Close Channel' icon on the 'Management' page under Channels, is not appearing clickable on mouse-over.
The mouse cursor, should convert into a 'hand', upon hovering over the icon.

**Comment by ShahanaFarooqui** [comment]
Fixed with Close channel icon clickable, changed text from 'disconnect' to 'close channel' and detach peer icon clickable
