### ISSUE TITLE
Columns wrapping over on the Invoices page

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#107]
Columns 'Create Date' and 'Settle Date' are wrapping over for the desktop resolution on the invoices page.
Resolution experiencing issue: 1920x1080 (16:9)

**Comment by ShahanaFarooqui** [comment]
Resolution 1920x1080, unable to reproduce. For IPad or less screen sizes (less then 730px): It is an expected behavior to wrap the dates, so that they will not overlap.
