### ISSUE TITLE
Session Timeout not working on Safari

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#111]
Session never times out on the Mac.

The RTL server is running locally and connects with the LND remote node.
Browser: Safari

**Comment by ShahanaFarooqui** [comment]
Opened the issue: https://github.com/rednez/angular-user-idle/issues/47

**Comment by ShahanaFarooqui** [comment]
The library owner closed above issue without any fix. Closing the issue for now, will consider to replace the library if issue persists for other users as well.
