### ISSUE TITLE
SSO with Linux PAM

### ISSUE THREAD

**Issue by tehelsper** [ShahanaFarooqui/RTL#115]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set a username to authenticate against the Linux user database. For example, I could name a user, like bitcoin, in the RTL.conf file and then without needing to store a copy of the plaintext password on the filesystem, I could log in with the bitcoin users's password.

**Describe the solution you'd like**
A native PAM solution would be preferable.

In RTL.conf, I'd like to see two new config lines that allow users to authenticate successfully against the Linux user database.

nodeAuthType=PAM
rtlPamUsername=bitcoin

Then, if the user logs into RTL with the password for the bitcoin user in Linux, they would be successfully authenticated.

**Describe alternatives you've considered**
An improved SSO explanation may help. I may not be fully understanding how the existing SSO auth works. I've used the PAM module in python a number of times, so allowing SSO to query a URL with the entered password and expecting a true/false response could work as well.

**Additional context**
N/A

**Comment by tehelsper** [comment]
There is a PAM node module I found, but I'm not an expert node developer.

https://www.npmjs.com/package/authenticate-pam

**Comment by ShahanaFarooqui** [comment]
Hi @tehelsper, thanks for the suggestion and we considered to implement the feature also. But, we faced below issues while trying to implement it and decided to not to move forward with it for now:

'authenticate-pam' library is not actively maintained.
npm is unable to install the library and the corresponding issue on their github is open for 5 months, with no response.
https://github.com/Rush/node-authenticate-pam/issues/27

In short, we cannot use above library and there is no other ready to use node library available for PAM authentication for now.

Regarding current SSO feature, please check: 
https://github.com/ShahanaFarooqui/RTL/blob/master/docs/Application_configurations
https://github.com/ShahanaFarooqui/RTL/issues/120

Current SSO works with https cookies only and we expect a wrapper application to pass the cookie in the url. For example BTCPayserver reads the cookie from the file location provided through docker and request for the url with that cookie.
