### ISSUE TITLE
Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!

### ISSUE THREAD

**Issue by goodc0re** [ShahanaFarooqui/RTL#116]
Running the latest version of rootzolls Raspiblitz https://github.com/rootzoll/raspiblitz 
with LND 0.5.2-beta and bitcoind v0.17.0.1 on mainnet
locally in my LAN, trying to connect via RTL while on the same LAN. 

Used the raspiblitz menu to install RTL, then edited the RTL.conf, see below
```
[Authentication]
macaroonPath=/mnt/hdd/lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
lndConfigPath=/mnt/hdd/lnd/lnd.conf
rtlPass=mypassword

[SSO]
rtlSSO=0
rtlCookiePath=/home/admin/RTL/cookies/auth.cookie
logoutRedirectLink=/login

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-pink
satsToBTC=false
bitcoindConfigPath=/mnt/hdd/bitcoin
enableLogging=true
port=3000
lndServerUrl=https://localhost:8080/v1
```

After editing the config I did this to restart RTL:
sudo systemctl stop RTL
sudo systemctl start RTL

sudo journalctl -f -u RTL then  shows
systemd[1]: Started RTL daemon.

I opened RTL in my browser http://192.168.0.113:3000/rtl/login
the RTL pass got accepted, but after entering the LND wallet password, I saw 

**"Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!"**

lnd.conf looks like
```
[Application Options]
debuglevel=debug
maxpendingchannels=5
alias=XXXXX
color=#XXXXXX
nat=false

# RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
# Domain, could use https://freedns.afraid.org
tlsextradomain=somedomain.mooo.com

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

[Bitcoind]
bitcoind.rpcuser=xxxx
bitcoind.rpcpass=xxxxx
bitcoind.rpchost=127.0.0.1
bitcoind.zmqpubrawblock=tcp://*:28332
bitcoind.zmqpubrawtx=tcp://*:28333

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6
```

**Comment by goodc0re** [comment]
The Raspiblitz is requiring lnd to be unlocked when it starts up, could that be the problem, it already being unlocked?

**Comment by Luigybruno** [comment]
Had the same problem. 
Try to renew the tls.cert and macaroons.
Raspiblitz main menu, _Export - Macarrons and TLS.cert_ and then _Reset - Renew macarrons and tls_. 
Worked for me

**Comment by saubyk** [comment]
@goodc0re you have two options to address this:

Option 1:
1. Comment `rpclisten=0.0.0.0:10009` in your lnd.conf
2. Restart lnd and unlock lnd
3. Access RTL from LAN, it should work

Option 2:
1. Add the below two lines in your lnd.conf after `rpclisten`
2. `restlisten=0.0.0.0:8080`; `tlsextraip=0.0.0.0`
3. Restart lnd and unlock lnd
4. Access RTL from LAN, it should work

Thanks.

**Comment by goodc0re** [comment]
Steps taking trying to solve the issue: 

- Tested Option 2: 
No change, original error remains. 

- Tried Luigybrusos suggestion
No change, original error remains

- Tested Option 1, also removing the changes from Option 2
No change 

Then I had the glorious idea to restart RTL 

sudo systemctl stop RTL
sudo systemctl start RTL

**RTL is now working** but regrettably I can't tell which of the solutions solved the problem. I should have restarted RTL after every Option I guess. 

I have another node (Litecoin mainnet) and I will attempt the steps there with restarting RTL in between to try and see if any single Option helps. : )

**Comment by goodc0re** [comment]
On the **litecoin** raspiblitz, none of the steps helped to run RTL, the error is the same: 
Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!

**Comment by goodc0re** [comment]
The lnd.conf that is currently working is as per Option 1: 

Comment rpclisten=0.0.0.0:10009 in your lnd.conf:

# rpclisten=0.0.0.0:10009

and also restart RTL: 

sudo systemctl stop RTL
sudo systemctl start RTL

Also allowing RTL some time to load is important, it can be quite slow to load the information.

**Comment by saubyk** [comment]
@goodc0re your problem is addressed. Closing this issue. Thanks.
