### ISSUE TITLE
Repeated payments of Empty invoice amount pay requests fails

### ISSUE THREAD

**Issue by obarat** [ShahanaFarooqui/RTL#118]
**Describe the bug**
When I try to pay multiple invoices with empty amount field (no defined `amt`).  It fails.  I get "payment in transition error".

**To Reproduce**
1. Get an invoice without a defined `amt`
2. Go to Payments
3. Paste the pay request
4. Enter the Satoshi amount
6. Get another invoice without a defined `amt`
7. Paste the pay request
8. Attempt to pay

**Expected behavior**
I should be able to make repeated payments of invoices with an undefined `amt`.

**Actual behavior**
First an error box appears for "payment in transition" and then a "payment success" message.  Then the UI loads forever.

**Your environment**
* version of `lnd`: 0.6
* operating system: Ubuntu
* version of `bitcoind`: 0.17

**Comment by ShahanaFarooqui** [comment]
@obarat Thanks for raising the issue. It has been fixed and released with v0.3.0.
