### ISSUE TITLE
Unconfirmed Balance problems

### ISSUE THREAD

**Issue by amcitaly** [ShahanaFarooqui/RTL#119]
**Describe the bug**
After close all the channels, 36 hours ago, now my funds are in the unconfirmed balance and it seems I can't move it

**Screenshots**
![unconfirmed balance](https://user-images.githubusercontent.com/46417649/55997344-7352f600-5cba-11e9-8141-a7d7a3f5da7a.PNG)

**Your environment**
Chain: Bitcoin [Mainnet]

LND Version: 0.5.2-beta on raspiblitz V 1.1

**Additional context**
I wonder if is just question of time or I mistake something, thank you

**Comment by saubyk** [comment]
Hi @amcitaly this is not an RTL issue. RTL is just showing you what the LND API is returning.

You should check the 'Pending' page in the Channels section. There should be some balance in 'Total Limbo Balance'. Try to reconcile the numbers there.
You can also see the pending blocks for your balance to be restored to your LND wallet.

**Comment by amcitaly** [comment]
Hi @saubyk thank you, well yesterday in fact all this amount was in the limbo space, today move to the unconfirmed balance. But I have moved twice 100000 sats, and it works, but if I try to move more it says "unsufficient funds"
![limbo balance](https://user-images.githubusercontent.com/46417649/55998197-916e2580-5cbd-11e9-8cb4-244a4cbb4e6c.PNG)

**Comment by amcitaly** [comment]
Ah I just saw now, It was confirmed the balance, than I moved 1M sats to my wallet and it works. Now the rest go back in unconfirmed, so is just question of patience, thank you
Look
![sent sast](https://user-images.githubusercontent.com/46417649/55998429-7a7c0300-5cbe-11e9-9b9d-0ed2f69cbb4a.PNG)
