### ISSUE TITLE
Show pending channels in Channels > Management

### ISSUE THREAD

**Issue by brmdbr** [ShahanaFarooqui/RTL#12]
When opening a channels the only screen where I can see that there are pending channels is the "pending" counter in the dashboard. It would be nice if those channels showed up in the Channels>Management screen.

**Comment by saubyk** [comment]
@brmdbr  will be adding a menu item for Pending Channels under Channels. Keeping the Pending channel list separate from Active and Inactive.

**Comment by brmdbr** [comment]
Awesome!

**Comment by ShahanaFarooqui** [comment]
@brmdbr This has been addressed, please pull again to update your RTL build. Thanks
