### ISSUE TITLE
Connecting without RPC password

### ISSUE THREAD

**Issue by torkelrogstad** [ShahanaFarooqui/RTL#120]
**Is your feature request related to a problem? Please describe.**
It should be possible to use RTL without specifying a RPC password. Manually supplying a username and password is not a secure solution. See the section "Secure authentication" in [Bitcoin Core doc on RPC security](https://github.com/bitcoin/bitcoin/blob/master/doc/JSON-RPC-interface.md). I believe LND uses the `.cookie` file described in the link above. 

**Describe the solution you'd like**
I'd like RTL to use macaroon files and `.cookie` for everything it needs with regards to bitcoind and lnd.

**Comment by ShahanaFarooqui** [comment]
@torkelrogstad
RTL is already enabled for SSO with cookie. It does not use the same cookie as generated by Bitcoin/LND but it generates its own cookie. The cookie gets regenerated after each use of RTL. It not only saves the hassle of login but also secures the application from shoulder surfing attacks. To not compromise user's data security, the SSO has only been enabled on https.

It can be configured through single/multi node config files. Sample configuration can be referred from:
https://github.com/ShahanaFarooqui/RTL/blob/master/sample-RTL.conf
https://github.com/ShahanaFarooqui/RTL/blob/master/sample-RTL-Multi-Node-Conf.json

Additionally, RTL is a browser application and cookie has to be passed via the url. This would require some sort of an application wrapper, which can read the cookie and pass to the browser. For example: in our integration with BTCPayServer, the authentication cookie is being passed by BTCPayServer and does not require a user to enter password for authentication.

Closing this issue for now, as the standalone authentication in RTL has to be done with a password only.

Do feel free to comment or open a new issue if you have any further ideas. Thanks.
