### ISSUE TITLE
[Invoices] Invoices list chronological limited to 100

### ISSUE THREAD

**Issue by seth586** [ShahanaFarooqui/RTL#123]
**Describe the bug**
RTL lists the first ~100 invoices. More recent invoices are not listed. I understand this is not a major feature point for RTL, but listing the last 100 would be much more useful. Once you hit 100 invoices, the page is worthless.

**Comment by ShahanaFarooqui** [comment]
@seth586 Thanks for raising the issue. It is fixed and merged in master and will be released in v0.3.1.
