### ISSUE TITLE
Not able to send Lightning payment

### ISSUE THREAD

**Issue by osilloh** [ShahanaFarooqui/RTL#126]
Tried to send Lightning payment to https://weareallhodlonaut.com fund.

I made several lightning payment attempts and they failed.

1. Changed the drop down payment option to Bitcoin (Lightning)
2. Copied the address info
3. pasted into payment field

This is what I saw. As I mentioned, I tried it a few times, the screen grabs may not be from the same attempt. 

<img width="814" alt="Screen Shot 2019-04-19 at 6 56 03 PM" src="https://user-images.githubusercontent.com/40921996/56517269-31a32600-64d8-11e9-86e0-c14be8ea18fd.png">

Each time I ended up with this timeout error

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/40921996/56517093-ceb18f00-64d7-11e9-92ef-dda1c765ccc0.png">

I then tried to send a payment to Satoshis.place and got the same error. Using Safari 12.1 and also tried it in Firefox version 66.0.2 for OSX.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/40921996/56517412-99597100-64d8-11e9-99d0-bbe82ba61d21.png">

RaspiBlitz v1.1 bitcoin Fullnode + Lightning Network
bitcoin v0.17.0.1 mainnet
lnd 0.5.2-beta

**Comment by saubyk** [comment]
Hi @osilloh are you getting the same error, when you try making the payment from LND command line?

**Comment by osilloh** [comment]
It just hangs.

COMMAND LINE: 
lncli --chain=bitcoin --network=mainnet sendpayment --force --pay_req=lnbc188390n1pwt4r06pp5dcws79l3snzvsyums5afsqy7wy8cdg6wp73fsxerwjnc8q0fga6qdyq2pskjepqw3hjqam9v9ex2ctvd35x7ervdahxzat5yq5y7unyv4ezqj2y8gsxxun0wajxvatwvskkzurstu69v4jhwe5hsefkg9p5gde40f5ys7nxv3q55cjzwpuyc53fcqzysxqzuy07jvtpvmzgk868yxpjgqk6z9su3625q026vs0lsspnyn9wfw9n8nkneqkktd4sthk5refk8r0ds9pj79a67ylwq3jz2y4wh0n2mez8gpspjx8d

RESULT (may wait in case of timeout):

**Comment by saubyk** [comment]
Hi, so the problem appears to be at LND level, not RTL.
RTL is just giving you back the response its getting from LND.

There can be many reasons for LND not able to make the payment.
1. Not having enough outgoing liquidity - do you have channels open with enough capacity?
2. Not having a path to the destination with enough liquidity - are you connected with at least a couple of nodes and have a few channels open with them?

**Comment by osilloh** [comment]
1. Think i do, the amount is small, 4/5 channels open.
2. Not sure about this.  How do i confirm this? I’m a noob. Can you plz point me to a link, i will google in the meantime.
3. Yes.

Thank you.

**Comment by saubyk** [comment]
You can check for the path to the destination, with `queryroutes` command.
You need to know the pubkey of the node you’re sending the payment to, for this.

You can execute:
`lncli queryroutes —dest=<pub key of the node> —amt=<amount you want to pay>

**Comment by saubyk** [comment]
Hi @osilloh closing this issue now, as its not really a RTL issue.
Feel free to open another one, in case you face further problems with RTL. Thanks.
