### ISSUE TITLE
Close Channel response not getting captured in the UI

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#129]
When closing the channels from RTL, in some cases, the API response is not getting captured by the UI, which results in the UI waiting and spinner running on the page.

**Comment by ShahanaFarooqui** [comment]
@saubyk Tried to reproduce the issue with 10 different channels and received the response for all 10 requests. Closing the issue now, please feel free to reopen with more specific steps to reproduce. Thanks.
