### ISSUE TITLE
[Feature Request] - Allow opening of private channels

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#130]
Open Channel api `POST /v1/channels` enables opening of private channels by setting a boolean flag (private) at the time of the api invocation.
When the open channel api is called with that flag on, it creates a private channel.

RTL should provide that option in the UI, to set the flag, while opening a channel.

Private channels are unique and are not advertised for routing on the network.
The channel list should also indicate which channels are private on the node.

**Comment by ShahanaFarooqui** [comment]
Done.
