### ISSUE TITLE
Transaction history shows CoinJoin from different wallet

### ISSUE THREAD

**Issue by SovereignNode** [ShahanaFarooqui/RTL#132]
**Describe the bug**
I transferred out my balance to Wasabi and Coin Joined that UTXO. My RTL tx history shows this CJ transaction in it's history

**To Reproduce**
1. Transfer all your funds from your lightning wallet to a bech32 Wasabi address
2. CoinJoin the UTXO

**Expected behavior**
The tx should not be visible in the RTL dashboard

**Actual behavior**
The tx shows up in RTL as a transaction to 109 recipients (in this particular case)

**Comment by saubyk** [comment]
Hi @SovereignNode 
This is a LND question. RTL is just showing you what the LND api for listing wallet transactions is returning.

Also, I am not sure about your expectation in this case. LND is showing the transaction record on the block. How can LND or even RTL make a determination to not show a particular transaction, which is recorded on the block. The idea of privacy should be coming from the obfuscation of the transaction on the block, which makes it difficult to trace back, which in your case you have accomplished.

Regardless, closing this issue as RTL will not be able to do anything in this case and it's better discussed in LND forums.

Thanks for your interest in RTL though and feel free to open tickets, if you face any other issues :-)
