### ISSUE TITLE
Litecoin support

### ISSUE THREAD

**Issue by P0u1us** [ShahanaFarooqui/RTL#133]
Hi, I am simply not getting the info from reading the docs, thus therefor my feature request question: does RTL support litecoin currently?
I am not able to get that working on my LTC-LND node.

I am getting all upto and including the login into RTL gui; thereafter it hangs on syncing.

**Comment by qprimed** [comment]
I am currently running a single RTL instance (using the multi-node config) against two litecoind full nodes with no issues.  RTL appears to support LTC natively.

**Comment by P0u1us** [comment]
OK, thnx, then I have to look further; I do have a distributed server setup, eg:
seperate Ubuntu server with full node LTC/LND
seperate Ubuntu server with full node BTC/LND
seperate Ubuntu server for BTCpayServer
seperate Win10 mgmt for RTL Chrome
all interconnected with an VPN mesh
so maybe there is something typical i need set in config?

**Comment by saubyk** [comment]
Hi @P0u1us are you able to connect RTL with your BTC/LND setup, but the LTC one is having issues?
or
You are not able to connect with any of the LND setups?

If RTL just hangs after login, its most likely not able to connect with the REST interface of LND. Please share your lnd.conf (do mask any sensitive info) to investigate further.

**Comment by P0u1us** [comment]
Pheww... bit of head scratching but got it working! ;-)
first got it working in the litecoin install: i am running litecoind with lnd together with RTL on the same server; and the client remote.
Then I had to copy the lnd.cond and bitcoin.conf files from the remote bitcoind system: and only left the typical lines (listen;tlsextraip;restlisten;rpclisten and user+pass) settings in there with the remote ipaddress of my bitcoind server.
amended the lot to RTL-Multi-Node-Conf.json and got that working ;-)
for me it is solved; 
however maybe a suggestion to simply allow manual setting of the remote restserver ip:port in the json?

**Comment by P0u1us** [comment]
AND... thanks for the response/support !

**Comment by saubyk** [comment]
Hi @P0u1us 
RTL config allows rest server ip:port config in the json file.
Please look at the documentation available below, if you are connecting nodes remotely:
https://github.com/ShahanaFarooqui/RTL/blob/master/docs/Multi-LND-Node-setup.md

Glad that your issue is addressed. Closing this issue now. Thanks.
