### ISSUE TITLE
[Invoices] Show the "settled" state of invoices

### ISSUE THREAD

**Issue by Phillo** [ShahanaFarooqui/RTL#136]
**Is your feature request related to a problem? Please describe.**
This is not a problem

**Describe the solution you'd like**
On the invoices section, all invoices are listed. However it is not possible to visually see which invoices have been settled or not. This could easily be done by providing a green or red background to all rows (green for settled, red for not settled"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ShahanaFarooqui** [comment]
@Phillo, Thanks for the suggestion. It is merged in master and will be released soon in v0.3.1.
