### ISSUE TITLE
[Invoices] Routing hints for private channel invoice

### ISSUE THREAD

**Issue by MaxHillebrand** [ShahanaFarooqui/RTL#137]
**Is your feature request related to a problem? Please describe.**
Apparently, the [creation of private channels is already finished](https://github.com/ShahanaFarooqui/RTL/issues/130), thanks @saubyk @ShahanaFarooqui!!
When running private channels, the public network does not know about the possible routes for sending payments to the private node. 

**Describe the solution you'd like**
The receiver can include routing hints within the invoice he provides to the sender.
`lncli addinvoice --private --amt <sat>`
Feature request to include a check box with `Include routing hint` in the `invoices` tab.

**Additional context**
Muh privacy.

**Comment by saubyk** [comment]
@ShahanaFarooqui The rest API for the same is:
`POST /v1/invoices`
We need to provide an option checkbox on the 'Invoices' page under the 'Add' button. The checkbox should be labeled as 'Private'.
When checked, it should invoke api with `private` flag as `true`.
This flags allows the user to control whether the generated invoice should include routing hints for private channels.

**Comment by ShahanaFarooqui** [comment]
@MaxHillebrand , Thanks for the suggestion. It has been committed in master and will be released with v0.3.1.
