### ISSUE TITLE
After adding a peer I need to refresh manually to see it in the table

### ISSUE THREAD

**Issue by brmdbr** [ShahanaFarooqui/RTL#14]
So yeah, title speaks for it self.

1. past uri in add peer box;
2. click add;
3. successfully added message shows, click Ok;

Table should be updated with new peer but isn't. Only after I refresh it shows.

**Comment by ShahanaFarooqui** [comment]
@brmdbr This has been addressed, please pull again to update your RTL build. Thanks.
