### ISSUE TITLE
How easy would it be to allow RTL to configure a brand new node?

### ISSUE THREAD

**Issue by Phillo** [ShahanaFarooqui/RTL#141]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
How easy would it be to adapt RTL to configure a brand new Lightning node with nothing configured? Things I think that would need configuring are:
Things found in lnd.conf like:
1. The name of the node 
2. The color of the node
3. Whether nat=true is set or whether
4. externalip is set

also other possibilities would be:
1. creating a new wallet and dealing with the 24 words generated (asking user to note them down)
2. Checking the status of the blockchain and the LND system and showing this back to the user, to inform him he may not go ahead until those two things are in sync

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by saubyk** [comment]
@Phillo 

Wallet initialization is now handled. This was covered with the below ticket:
https://github.com/ShahanaFarooqui/RTL/issues/135

The feature is now available with release 0.4.1

Rest of the suggestions are not covered now. Will be adding these features in the later releases.

**Comment by ShahanaFarooqui** [comment]
@Phillo, Thanks for suggesting the feature, we are now closing the issue as init wallet feature is released with v0.4.1. We are not planning to edit the LND configuration through UI in near future.
