### ISSUE TITLE
command "node rtl" ends with module errors

### ISSUE THREAD

**Issue by kklara** [ShahanaFarooqui/RTL#142]
**Describe the bug**
Hello, this is most likely problem on my side, but I am not familiar with neither node nor RTL so I would very much appreciate your help with this. I followed this guide to install LND+RTL on FreeNAS https://github.com/seth586/guides/blob/master/FreeNAS/freenas_6_rtl.md
LND is working but RTL is not. The service seems to be running but is not responding and when started manually ends with module load error, see bellow. Thanks for any help.

**To Reproduce**
1. Following the guides in https://github.com/seth586/guides/blob/master/FreeNAS/freenas_6_rtl.md
(with previous guides setting LND and Tor as well)

Connect to IP:3000 where RTL should respond but nothing happens.
starting rtl manually eds with this error:
```
root@lnd:~ # node rtl
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module '/root/rtl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
```

**Your environment**
* version of `lnd` 0.6.1-beta commit=v0.6.1-beta-rc2
* operating system FreeBSD 11.2-STABLE
* version of  bitcoind 0.18

**Comment by saubyk** [comment]
Hi @kklara 
Can you please confirm if `npm install` ran successfully?

Also, the command `node rtl` needs to be run in the rtl folder where you ran the `npm install` command.

Thanks.

**Comment by kklara** [comment]
Hi @saubyk ,

This is result of `npm install `run from **~/rtl**: 
```
root@lnd:~/rtl # npm install
npm WARN saveError ENOENT: no such file or directory, open '/root/rtl/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/rtl/package.json'
npm WARN rtl No description
npm WARN rtl No repository field.
npm WARN rtl No README data
npm WARN rtl No license field.

```
followed by `node rtl`:
```
root@lnd:~/rtl # node rtl
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module '/root/rtl/rtl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11

```

Directory ~/rtl contains 2 files:
`RTL.conf` and `package-lock.json`
and directory `RTL-0.3.0` which is extracted release

**Comment by saubyk** [comment]
Hi @kklara ,
rtl directory should not be just these 2 files.
Please clone the repo again and run the install steps.
Specifically the below from @seth586 's guide:
```
# cd ~
# wget https://github.com/ShahanaFarooqui/RTL/archive/v0.3.0.tar.gz
# tar -xvf v0.3.0.tar.gz
# rm v0.3.0.tar.gz
# mkdir ~/rtl
# mv RTL-0.3.0 rtl
# cd rtl
# npm install
```

**Comment by kklara** [comment]
Soo progress :) following @seth586 's steps (copy & paste one by one) results in this directory structure:
```
 ~ <-- actually /root
     /rtl <-- no files here, only package.lock after npm install
           /RTL-0.3.0  <-- all files are here
```
Which is appareantly not what is expected, so either there is mistake/bug by Seth or my shell insteprets mv command differently.

When I executed `npm install` from  `~/rtl/RTL-0.3.0 ` it looks like it installed RTL successfully.

But this probably breaks other parts of Seth's guide like the rc.d service which contains this:
`rtl_command="/usr/local/bin/node /root/rtl/rtl"`

so if I undertand correctly the content should be in /root/rtl/ (becuase the last "rtl" in "/usr/local/bin/node /root/rtl/rtl" is just "name" and not another directory, right?

**Comment by kklara** [comment]
After I moved content of ~/rtl/RTL-0.3.0 to just ~/rtl/ (using mc :) everything is working, I have RTL running
Thanks for helping me @saubyk 
I will comment on @seth586 repo as well if someone has the same problem.

**Comment by seth586** [comment]
Just saw this, I will try to duplicate and update my guide. 

Either 'mv' or the tar extraction is duplicating the folder structure.
