### ISSUE TITLE
Most recent invoices not visible

### ISSUE THREAD

**Issue by hubiktomas** [ShahanaFarooqui/RTL#144]
**Describe the bug**
When I open the Ride the Lightning interface, I do not see the most recent invoices. I can see the older ones (approx till the end od November 2018). When I try to create a new Invoice, it gets created and I can see it in the interface, but after page refresh, it is gone. I can see it using the command line interface.

**To Reproduce**
1. Open the Ride the Lightning interface
2. Click on Invoices
3. Most recent invoices are not visible

**Expected behavior**
All the invoices should be visible.

**Actual behavior**
Only invoices till the end of November 2018 are visible.

**Your environment**
* I am using the Ride the Lightning bundled with the BTCPayServer v1.0.3.97
* LND 0.6.0-beta
* Ride the Lightning 0.3.0-beta
* operating system Linux BTCPayServerVM 4.18.0-1014-azure #14~18.04.1-Ubuntu SMP Mon Mar 18 16:15:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind 0.18.0

**Additional context**
Not sure if it is relevant, but when I click Payments, I can see the loading bar, but it never stops loading.

**Comment by ShahanaFarooqui** [comment]
@hubiktomas, Please update RTL version to 0.3.1-beta. It has been fixed with issue #123. 

But, if you are using 'DEFAULT' authentication type for login, then please wait for 1-2 hours for new bug fix release v0.3.2-beta.

**Comment by hubiktomas** [comment]
Ok, thank you.

**Comment by ShahanaFarooqui** [comment]
Hi @hubiktomas, v0.3.2 has been released, which has the fix for #123 and #143 as well. Thanks.
