### ISSUE TITLE
The default invoice list does not seem to show the correct invoices and also does not scroll

### ISSUE THREAD

**Issue by Phillo** [ShahanaFarooqui/RTL#146]
**Describe the bug**
The Invoice menu does not show recent invoices, and there is no way to change the sort settings to see recent ones. Also, only one screen of invoices is shown, no more

**To Reproduce**
1. Create many invoices and settle (i.e. pay) them
2. Click on Invoices
3. Search for the recent invoices that were settled

**Expected behavior**
You expect to see the latest invoices and be able to scroll down the screen to see ALL other invoices

**Actual behavior**
Instead the sorting of the invoices is a bit random - I can't work out what is being used to sort them, but for sure I cannot see the last invoices, nor can I scroll down the screen to see all other invoices.

**Screenshots**

**Your environment**
* version of `lnd` 0.6.0-beta
* operating system (`uname -a` on *Nix) Linux RaspiBolt2 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend Bitcoin Core Daemon version v0.17.1
* any other relevant environment details

**Additional context**
N/A

**Comment by ShahanaFarooqui** [comment]
Which RTL version are you using? V0.3.2 is the latest version and it has pagination on Invoices. Please get the latest rtl release and it should fix your issue.

**Comment by Phillo** [comment]
hi there, i should have the most up-to-date version. Where can i see this?

I just tested a little more and discovered that if i use the arrow keys or page down to scroll that it works fine, but something is blocking the scroll wheel on my mouse from working as it should. Also there is no scroll bar showing on the right hand side to indicate the fact I could scroll down...

**Comment by Phillo** [comment]
Another comment: i just noticed that the "no scroll" feature is only on Firefox. Annoying, though as this is my main browser. If you have a way of fixing it that would be fantastic!! Thanks!!

**Comment by ShahanaFarooqui** [comment]
@Phillo, You can check release details at https://github.com/ShahanaFarooqui/RTL/releases.
Regarding Firefox, we are unable to reproduce the error at our end, the firefox scroll is working perfectly with arow key, up/down keys and mouse scroll wheel.
