### ISSUE TITLE
"Refresh" feature required for home page

### ISSUE THREAD

**Issue by Phillo** [ShahanaFarooqui/RTL#147]
**Is your feature request related to a problem? Please describe.**
This is almost a problem, but perhaps not quite. Basically, once the home page is called and some information is changed, i.e. an invoice has been paid, this new information (in this case channel balance has changed) is not shown.

**Describe the solution you'd like**
There are two solutions: one is to have a refresh button that refreshes all data pertinent to the screen at hand. The other is to have a refresh button per panel, which avoids having to update the whole screen, but instead update just the infos one needs updated..

This also applies to, e.g. the invoices page. If an invoice is settled, this new state is not shown at all in the table on the right-hand side of the screen.

**Describe alternatives you've considered**
See above section

**Additional context**
N/A

**Comment by saubyk** [comment]
@Phillo 

The scenario which can be handled reasonable is when the payments are made via the node. Upon a successful payment, the following sections will be automatically refreshed:
1. Home Page - Local-Remote Balances (already handled)
2. Home Page - Channel Balance
3. Channels > Management - Channel list

**Comment by ShahanaFarooqui** [comment]
Done with Home Page - Channel Balance update.
Home Page - Local-Remote Balances (already handled)
Channels > Management - Channel list (already handled)

Will be released with v0.4.2.
