### ISSUE TITLE
Password Validation Failed! when Send Funds v0.3.2

### ISSUE THREAD

**Issue by royalgarter** [ShahanaFarooqui/RTL#149]
**Describe the bug**
When I tried to Send Funds in LND Wallet, after input the login password this popup occurred
Authorization Failed
Code:401
Message:Password Validation Failed! 

**To Reproduce**
1. Go to 'LND Wallet / Send Receive'
2. Input Address, Fee, choose SweepAll
3. Click 'Send', input login password

**Your environment**
* lnd version 0.6.1-beta commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b
* Ubuntu 18
* bitcoind v0.17.1
* rtl 0.3.2-beta commit 1ff29ebfc0961771ac1b85bd2ddec9b269fae11c

**Debug**
After tracking network request, I saw the format of authorize request (/rtl/api/authenticate) when Send Funds is Base64 (length=20), meanwhile the first login request is Hex (length=64)

**Comment by ShahanaFarooqui** [comment]
Hi @royalgarter. Yes, just realized that it could have broken with our 0.3.1 release. I will fix and publish the code by today eod. Thanks for raising the issue.

**Comment by royalgarter** [comment]
Thanks @ShahanaFarooqui , looking forward to test your new release 👍

**Comment by ShahanaFarooqui** [comment]
@royalgarter Version 0.3.3 has been released with this fix. Closing the issue now, please get the latest release and feel free to reopen if issue still persists.
