### ISSUE TITLE
Allow the payment page to have a "paste" button to send the clipboard as the payment field

### ISSUE THREAD

**Issue by Phillo** [ShahanaFarooqui/RTL#151]
**Is your feature request related to a problem? Please describe.**
Add a "paste" option to the standard payment page

**Describe the solution you'd like**
When requesting a payment, there is a "send" button which activates once a payment text has been entered in the relevant field. When I am mobile I will have almost ALWAYS copied this value from another site / app. I would suggest that the default action for "send" is to "paste" anything on the clipboard into that field. Once this is done, the button reverts to being the "send" button for the payment just pasted. If one or more characters are typed into the empty "payment" field, the button also reverts to its normal "send" functionality.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ShahanaFarooqui** [comment]
@Phillo. Thanks for the suggestion but we decided to not to enhance this feature for now as it will require interaction with OS clipboard and will be very device dependent. This will add very less value after investing a lot of time. Due to time scarcity, it will be better to invest this time for other feature updates.

**Comment by Phillo** [comment]
Hi there,

Just saw the reply. I guess I had thought that since RTL already implemented the copy feature for copying things like pub_node ids that the paste feature would be just as easy.

My bad, I guess...

**Comment by ShahanaFarooqui** [comment]
@Phillo, we are currently using RTL’s own clipboard to copy paste within RTL. But, when user wants to copy the data from outside RTL, that data gets copied at the operating system’s clipboard and RTL has to interact with os clipboard to get the copied data from there. RTL is running on multiple devices, browsers and to handle this interaction and test it with all the scenarios will be very time consuming. But thank you for the suggestion and we will try to implement it after other critical improvements. Hope this explains our view more clearly.

**Comment by Phillo** [comment]
No I understand completely why it's a pain and won't hold my breath to getting it soon, no worries at all.

I am glad that you do have the copy icon's for things like invoices and the pub_node id too as i do paste this in other applications or websites on my smart phone. I had assumed that that icon was a simple HTML component and naively thought the paste component would be equally simple to add.

I stand corrected :)
