### ISSUE TITLE
It would be nice to show how long a pending forced closed channel has left until maturity

### ISSUE THREAD

**Issue by Phillo** [ShahanaFarooqui/RTL#152]
**Is your feature request related to a problem? Please describe.**
Would it be possible to include the "blocks til maturity" stat with forced closed pending channels?

**Describe the solution you'd like**
It is possible in RTL to list all pending channels, however, these can take days to reach maturity. A good way to let the user know how long he has left to wait is to show the "blocks til maturity" stat, gained from the `lncli pendingchannels` command.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by saubyk** [comment]
Hi,
'Blocks till Maturity' field is available in 'Pending Force Closing Channels' section of the 'Pending Channels' page.
Closing this issue.
Thanks.

**Comment by Phillo** [comment]
Hi,

I think I figured out why I can't see it. I tend to use RTL on my phone and it seems to have the habit of not showing the same information as on a larger screen...

Thanks
P

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by saubyk** [comment]
Hi @Phillo 
We have reduced the number of fields displayed in the grid with mobile resolution, to improve readability.
You can click/touch on the record and it will show all the details including the 'Blocks Till Maturity' value.
Hope that helps.

Thanks.

**Comment by Phillo** [comment]
Hmmm there might be a small bug there then. From memory whenever I click a row on a mobile screen it often brings up the reduced columns only.

Guess I'll have to do some testing and raise a proper defect then (yep I'm an I.T. Tester!) If I can reproduce it...

Sent from Nine<http://www.9folders.com/>
________________________________
