### ISSUE TITLE
Refresh on channel closure and force close option

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#153]
**Describe the bug**
1. Refresh the app, after a channel is closed, to ensure all the sections are updated to reflect the current status of channels.
2. 'Force close' option should only be used for inactive channels.

**Expected behavior**
Once a channel is closed, the home page, and the channels page should be refreshed automatically.

**Comment by ShahanaFarooqui** [comment]
Done, pushed in master.
