### ISSUE TITLE
RTL prioritizes IPv4 over .onion when .onion peer is requested

### ISSUE THREAD

**Issue by elkimek** [ShahanaFarooqui/RTL#154]
**Describe the bug**
Connecting t peer prioritizes IPV4 over onion addres even if .onion peer address is requested

**To Reproduce**
1) Connect to peer which has both IPv4 and .onion address available via .onion address

**Expected behavior**
.onion peer should be connected to

**Actual behavior**
Got connected to IPv4 instead

**Screenshots**

**Your environment**
* 0.6.1beta`
* nodl

**Additional context**
Replicated by user from LND slack

**Comment by saubyk** [comment]
@elkimek 
The api we use to connect with network peers is `POST /v1/peers`:
documentation at : https://api.lightning.community/rest/index.html?shell#v1-peers

This api does not have any options to control over which address to connect with.
This issue may best be addressed with LND.
