### ISSUE TITLE
Macaroon not sent on remote connection

### ISSUE THREAD

**Issue by axelaxek** [ShahanaFarooqui/RTL#158]
**Describe the bug**
Macaroon is not being set for remote connections

**To Reproduce**
1. Go to the login page
2. Open de developer tools (Chrome browser)
3. Enter Login in credentials
4. click on login
5. observe the network tab on the developer tools: authentication is performed correctly but the enxt call GetInfo fails with:
```
{"message":"Fetching Info failed!","error":{"error":"expected 1 macaroon, got 0","code":2}}
```

**Expected behavior**
Macaroon should be sent with the request

**Actual behavior**
Macaroon is not being sent

**Screenshots**
![image](https://user-images.githubusercontent.com/4200291/59468498-8016d600-8e32-11e9-94f1-f79860f9dc07.png)

**Your environment**
* I'm runnig RTL on a Manjaro linux box
* I runned npm install from the master branch
* I'm trying to connect to a remote Raspiblitz Version 1.2 with lnd 0.6-beta and bitcoin 0.17.

**Additional context**
RTL config:
```
[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login

[Authentication]
macaroonPath=/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
nodeAuthType=CUSTOM
rtlPass=123456
lndConfigPath=./lnd.conf
rtlPassHashed=8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=https://10.0.0.1:8080/v1
bitcoindConfigPath=./bitcoin.conf
enableLogging=true
port=3000

```

Authentication Token:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2luZ2xlX05vZGVfVXNlciIsImxuZENvbmZpZ1BhdGgiOiIuL2xuZC5jb25mIiwibWFjYXJvb25QYXRoIjoiL2hvbWUvYml0Y29pbi8ubG5kL2RhdGEvY2hhaW4vYml0Y29pbi9tYWlubmV0L2FkbWluLm1hY2Fyb29uIiwiaWF0IjoxNTYwNDU5ODMyfQ.nDnYyKlbtXA2PY09r805IImgyIjIwPQjCHndLvGCYxM
```

**Comment by axelaxek** [comment]
more logs (even after being logged in successfuly )
```
Calling getinfo from lnd server url: INFO: https://172.16.0.156:8080/v1/getinfo
Console: 
Switch: 14: 1560461545384: INFO: Switch Post Options: {"url":"https://172.16.0.156:8080/v1/switch","rejectUnauthorized":false,"json":true,"form":"{\"end_time\":\"1560461545\",\"start_time\":\"1557869545\"}"}
Console: 
Switch: 28: 1560461545403: ERROR: Switch Post Error: {"name":"StatusCodeError","statusCode":500,"message":"500 - {\"error\":\"expected 1 macaroon, got 0\",\"code\":2}","error":{"error":"expected 1 macaroon, got 0","code":2},"options":{"url":"https://172.16.0.156:8080/v1/switch","rejectUnauthorized":false,"json":true,"form":"{\"end_time\":\"1560461545\",\"start_time\":\"1557869545\"}","method":"POST","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":500,"body":{"error":"expected 1 macaroon, got 0","code":2},"headers":{"content-type":"application/json","trailer":"Grpc-Trailer-Content-Type","date":"Thu, 13 Jun 2019 21:32:25 GMT","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"172.16.0.156:8080","port":"8080","hostname":"172.16.0.156","hash":null,"search":null,"query":null,"pathname":"/v1/switch","path":"/v1/switch","href":"https://172.16.0.156:8080/v1/switch"},"method":"POST","headers":{"content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":51}}}}

```

**Comment by saubyk** [comment]
@axelaxek 
Can you please provide some more details about your setup?
Where is RTL running?
Is it running on the pi?
where are you opening the browser from?
Looks like `lndServerUrl` field is not correctly configured in the `RTL.conf' file. It should have the correct IP address pointing to the LND http server.

Also, it would help, if you can share you lnd.conf file (do mask the sensitive info).

**Comment by saubyk** [comment]
@axelaxek  depending on your setup, you may need to tweak your `lnd.conf` also.
It should have the `restlisten` parameter configured, so that RTL can connect to the LND http server.

**Comment by saubyk** [comment]
@axelaxek assuming this issue has been addressed.
closing now. feel free to re-open if the issue still persists. Thanks.
