### ISSUE TITLE
[GUI] pinned menu does not stay pinned

### ISSUE THREAD

**Issue by MaxHillebrand** [ShahanaFarooqui/RTL#165]
**Describe the bug**
On startup, the menu is hidden - when I pin it, then it is fixed - but when I reload the page, then it's hidden again.

**Expected behavior**
Keep it fixed when I click the pin icon.

**Your environment**
* `RTL` 3.1-beta
* `lnd` 6.1-beta
* `OS` Debian 10
* `bitcoind` 0.18

**Comment by saubyk** [comment]
@MaxHillebrand, the pin icon is to pin the menu temporarily.
To change it permanently, you can click on the rotating settings icon on the right, update the pin slider setting and click on save.

**Comment by MaxHillebrand** [comment]
Oh, fantastic, this works! 
Thanks, closing the non-issue :)
