### ISSUE TITLE
Remove secure attribute of the cookie from BTC payserver SSO setting

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ShahanaFarooqui/RTL#168]
@NicolasDorier 
Remove secure attribute of the cookie if the user accesses the API via `http:`.
Related to BTCPayserver PR: https://github.com/btcpayserver/btcpayserver-docker/pull/172

We have taken a different approach to address this issue. Instead of using the browser based cookie, we are now sending the access_key in the request body. It is saving us from worring about the protocol and browser's handling of the data.

Implemented solution:
- [ ] Removed cookie from the authentication request,
- [ ] Passing the Sha256 encrypted access_key in the body.password.
- [ ] Server authenticates with encrypted password and sends back the JWT token for the future API calls.
- [ ] If user is authenticated successfully, then the server will refresh the cookie in the cookie file, so that the same cookie can not be used again. This will save the user from shoulder surfing attacks and from the browser history's saved access key attack.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier 
Released above solution with v0.4.3. Please check and let us know if this works.

**Comment by NicolasDorier** [comment]
cool will test it ping @wiz

**Comment by NicolasDorier** [comment]
tested, not RTL works fine!
