### ISSUE TITLE
[Feature request] Docker support for ARM64

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#174]
Is it possible to add support for ARM64? Quite easy now you already did arm32.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier, Please check v0.4.7 with arm64 support and let us know if this works.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui thanks, you need to fix https://github.com/ShahanaFarooqui/RTL/blob/master/Dockerfile.arm64v8#L3  with the arm64 version of tini.

**Comment by ShahanaFarooqui** [comment]
Updated the tini image to arm64, please check v0.4.7 again.

**Comment by NicolasDorier** [comment]
Will try monday when I am in front of my board.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier Hi, did you get some time to try?

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui yes sorry it takes more time than expected. My board not working like I want, will do today or tomorrow.

**Comment by NicolasDorier** [comment]
Sorry again for taking time. I got problem with the image, tried to fix it but it turned out this was because I was using docker for ARM32 for running the ARM64 image. :(

Will try again tomorrow, with the right docker architecture.

**Comment by NicolasDorier** [comment]
Works
