### ISSUE TITLE
Bundle fonts in the app or make it usable with default browser fonts.

### ISSUE THREAD

**Issue by chokoboko** [ShahanaFarooqui/RTL#176]

**Comment by ShahanaFarooqui** [comment]
@chokoboko I am not sure about the issue here. We are already importing Roboto font directly from 'https://fonts.googleapis.com', so fonts should readily be available. No explicit bundling is required. Can you please explain the requirement in more detail?

**Comment by chokoboko** [comment]
Sorry I wasn't clear enough. It may be a personal view, but I don't like calling googleapis.com each time I open RTL. Browsers send personal info ("Referer", "User-Agent", etc.).

**Comment by ShahanaFarooqui** [comment]
@chokoboko thanks for raising a great point. It was just force of habit to use google fonts. 

We were using Roboto and Material Design fonts through googleapi import. The api import has been replaced with local font installation now. The fix has been merged in master and will be released with v0.4.8 soon.
