### ISSUE TITLE
Question: Can RTL be used to complete LND initial setup? 

### ISSUE THREAD

**Issue by muhepd** [ShahanaFarooqui/RTL#180]
Hi,

I want to first say, thank you for your very good job on RTL, it's very good.

My question is related to LND initial setup through RTL. After completing the "make install" process and pre-configuring the lnd.conf file, we need to launch LND and execute "lncli create" and go through the password/24-word seed steps and then unlock the wallet.

The question is, can that initial lncli create steps be done through RTL instead of CLI?

Just want to find an friendly way to do this step.

Thanks.

M.

**Comment by saubyk** [comment]
Hi @muhepd 
Yes, RTL handles the `lmcli create` step as well.
You just need to ensure that `lnd.conf` and `RTL.conf` are configured correctly per the instructions provided.

RTL will take you through the steps of generating your password and 24 word seed.

Closing this issue now, as there is no action required for us to take on this. If you have more questions please feel free to re-open or open new ones.
Thanks.

**Comment by ShahanaFarooqui** [comment]
@muhepd, thanks for the appreciation and suggestion.
Though RTL has create wallet feature and can create a new wallet, we would not recommend to use RTL's init wallet feature if you want to generate the seed with `aezeed_passphrase`. 

We already have opened 2 tickets with LND and waiting for a solution/advice from them:
'https://github.com/lightningnetwork/lnd/issues/3168' 'https://github.com/lightningnetwork/lnd/issues/3128' .
