### ISSUE TITLE
Unable to refresh the page without being logged out in SSO

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#181]
In BTCPay, when I connect to RTL, there is no way I can refresh the data on the screen. 

Trying to refresh the page will give a `Login Failure! ` which means I need to browse again to the RTL page in BTCPay to log in again.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier, After debugging the code, i realized that we explicitly added the logic to logout the user on page refresh. We added this logic with the requirement to refresh the cookie after every use. It looks like, I assumed that the user should not be able to refresh the page without access-key.

With latest commit, we have updated the logic to

a) Authenticate the user through 'access-key' if it exists in the url. 
b) If access-key is absent in the url (F5 or unauthenticated user), then the application will read the session token and verify that from server. 
c) If the user has already been authenticated then the page refresh will be able to successfully verify the token and the application will keep work. 
d) If the user is not authenticated then access-key and token both will be missing and server will deny all the requests.

This has not been released yet. I need to fix one more bug before releasing it tomorrow. So let us know if anything else need to be included/updated with above flow.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I can build myself from master and test your fix when you feel like it. Let me know when.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier you can test it right away. The side menu’s child toggle is a bit wacky which I will fix today. But this issue’s updates are complete and ready to test.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I tested it, and it work as expected. Let me know when you do a new version.

**Comment by ShahanaFarooqui** [comment]
Released with v0.5.1.
