### ISSUE TITLE
C-lightning: List payments is not working

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#185]
Not able to view the list of payments made on the payments page.

**Comment by saubyk** [comment]
@ShahanaFarooqui this issue might be occurring in the master branch or the next release candidate of c-lightning.

Please refer to the below issue:
https://github.com/saubyk/c-lightning-REST/issues/18

**Comment by ShahanaFarooqui** [comment]
As discussed, list payments is working with clightning version 7.2.0 but not with Master branch. Keeping the issue open till clightning's next release to track and update the endpoint, if needed.

**Comment by saubyk** [comment]
This issue should be addressed with release v0.0.4 of cl-rest and c-lightning v0.7.3
