### ISSUE TITLE
error Istrusted : true at login

### ISSUE THREAD

**Issue by DoktorWhat** [ShahanaFarooqui/RTL#187]
**Describe the bug**
Since I updated to raspiblitz v1.3 I can't log in to RTL without getting some errors first. After the error message I am completely unable to reach the site for a while.

**Expected behavior**
Log in to RTL.

**Actual behavior**

When I try to log in to RTL I am getting the error message Istrusted : true:

**Screenshot**
![error_Istrusted](https://user-images.githubusercontent.com/33834800/66258249-205a8700-e7a3-11e9-9a0c-8b33a903c6d4.jpg)

Then the site is down

**Screenshot**
![refused_to_connect](https://user-images.githubusercontent.com/33834800/66258308-fce40c00-e7a3-11e9-9297-792dad6d9876.jpg)

After about 1 min I can reach the site again and everything works fine.

**My environment**
* version of `lnd v0.7.1-beta`
* operating system (`raspiblitz v1.3` on *rpi 3)
* version of `bitcoind v0.18.1`

Error log:

![RTL_Error](https://user-images.githubusercontent.com/33834800/66258354-9e6b5d80-e7a4-11e9-9e0f-aa1e61c85ff9.jpg)

'npm install' errors:

![RTL_Error2](https://user-images.githubusercontent.com/33834800/66258356-a0cdb780-e7a4-11e9-8fd9-6d98bbaf310a.jpg)

**Additional context**

'npm audit' output

[npm_audit.txt](https://github.com/ShahanaFarooqui/RTL/files/3693526/npm_audit.txt)

**Comment by ShahanaFarooqui** [comment]
@DoktorWhat, Above issue consists multiple different issues, so let us address them one by one:

1) npm install errors: 
-     Delete ./RTL/node_modules folder.
-     Execute 'sudo npm install --unsafe-perm' instead. It is not "unsafe" to install dependencies with this flag. 
- 
    unsafe-perm References:
        https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/ 
        https://nutcrackerz.in/2018/08/17/what-is-unsafe-perm-flag-in-npm/

Being unable to install npm dependencies can also be a reason for RTL to fail. So, please resolve this issue before running the application.

2) isTrusted error:
    This error is usually associated with cross-domain request headers (CORS). RTL server cannot be the reason or solution for this issue. We need more information to understand the root cause:
    Are you serving RTL behind any other server? like nginx? 
    Which browser are you using to open RTL?

3) Site can't be reached:
Looks like this is the time when your RTL.service is trying to restart 'RTL deamon' after getting status=1/FAILURE.

4) RTL Logs:
RTL Logs also indicate that the issue should be due to your admin access/firewall/some connection configuration.

**Comment by DoktorWhat** [comment]
1. I deleted the node_modules folder and executed 'sudo npm install --unsafe-perm'. Still getting warnings and severity vulnerabilities.

![error3](https://user-images.githubusercontent.com/33834800/66302649-93761180-e8f9-11e9-9647-33a24367e053.jpg)

2. I have a BTCPayServer that runs RTL as well. 

I have not tempered with any RTL configs on my Raspiblitz tho. Just installed it after updating to v1.3

The browser doesn't cause the problem, same issue on different browsers.

4. I haven't changed any router configurations since the update. All ports are forwarded correctly.

**Comment by saubyk** [comment]
@DoktorWhat 
There was a bug in the authentication logic. We have fixed the issue and tagged a new release v0.5.3
https://github.com/ShahanaFarooqui/RTL/releases/tag/v0.5.3

You can download the latest release to get the issue addressed.

**Comment by saubyk** [comment]
@DoktorWhat assuming the issue is addressed now. Closing this issue.
Feel free to re-open if you face the same issue again. Thanks.
