### ISSUE TITLE
Problem with the Node.js version (not compatible with RTL)

### ISSUE THREAD

**Issue by babonet13** [ShahanaFarooqui/RTL#192]
I got this : 
satoshi@naka-dev:~/RTL$ sudo npm install
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

How to come back to a previous version of Node.js ?
(I can not find a way to desinstall Node.js properly ...)

**Comment by saubyk** [comment]
Hi @babonet13 
You seem to be running a much older version of npm.
you should upgrade your npm version, instead.

**Comment by babonet13** [comment]
Here are the output on my machine :

satoshi@naka-dev:~$ sudo apt-get install npm
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
npm est déjà la version la plus récente (5.8.0+ds6-4).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 65 non mis à jour.

satoshi@naka-dev:~$ npm -v
5.6.0

The system says that I'm up-to-date !?

**Comment by saubyk** [comment]
npm's latest version is 6.12.0.
https://github.com/npm/cli/releases/tag/v6.12.0

Please try this `sudo npm install npm@latest -g`

**Comment by babonet13** [comment]
Seems to be good ... but the version number is not updated 

satoshi@naka-dev:~/RTL$ sudo npm install npm@latest -g
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js                                                
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.12.0                                                                                                        
updated 1 package in 3.424s
satoshi@naka-dev:~/RTL$ npm -v
5.6.0

**Comment by saubyk** [comment]
try this:
`sudo npm cache verify` and then check the version.

**Comment by babonet13** [comment]
Same result :

satoshi@naka-dev:~$ sudo npm cache verify
Cache verified and compressed (~/.npm/_cacache):
Content verified: 1703 (232721439 bytes)
Index entries: 1733
Finished in 5.913s

satoshi@naka-dev:~$ npm -v                                                                                          
5.6.0

**Comment by babonet13** [comment]
Seems better, because I no do find the problem aboud the version ... but there is some WARN

satoshi@naka-dev:~$ sudo npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/satoshi/package.json'                             
npm WARN enoent ENOENT: no such file or directory, open '/home/satoshi/package.json'                                
npm WARN satoshi No description
npm WARN satoshi No repository field.
npm WARN satoshi No README data
npm WARN satoshi No license field.

audited 12262 packages in 3.49s                                                                                     
found 0 vulnerabilities

**Comment by babonet13** [comment]
And I can start the RTL server ...

**Comment by babonet13** [comment]
I can log using my RPC password, ... but the Wallet unlock fail 
![Capture d’écran 2019-10-14 à 18 07 47](https://user-images.githubusercontent.com/20139338/66766111-a1093980-eead-11e9-987c-a5d5e8b619be.png)

**Comment by saubyk** [comment]
is LND running and unlocked?

**Comment by babonet13** [comment]
You're right, LND deamon crashed ... I just restart it ... I seems working now ...

**Comment by babonet13** [comment]
Thanks fo support

**Comment by babonet13** [comment]
r

**Comment by saubyk** [comment]
Welcome. Closing this issue now.
