### ISSUE TITLE
Installation issue on CentOS 7

### ISSUE THREAD

**Issue by babaiants** [ShahanaFarooqui/RTL#195]
**Describe the bug**
Cannot compile the code. The "npm install" command gives me errors.
Installed CentOS "Development Tools" (gcc, gcc++ and so on) but it did not help. 

**Your environment**
* operating system: CentOS 7 (updated)
* any other relevant environment details: node-v8.16.2

[root@flashlight RTL]# npm install

> node-sass@4.12.0 install /opt/gocode/src/github.com/RTL/node_modules/node-sass
> node scripts/install.js

Unable to save binary /opt/gocode/src/github.com/RTL/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/opt/gocode/src/github.com/RTL/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/opt/gocode/src/github.com/RTL/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/opt/gocode/src/github.com/RTL/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/opt/gocode/src/github.com/RTL/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/opt/gocode/src/github.com/RTL/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/opt/gocode/src/github.com/RTL/node_modules/node-sass/vendor' }

> node-sass@4.12.0 postinstall /opt/gocode/src/github.com/RTL/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/lib/nodejs/node-v8.16.2-linux-x64/bin/node /opt/gocode/src/github.com/RTL/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/lib/nodejs/node-v8.16.2-linux-x64/bin/node',
gyp verb cli   '/opt/gocode/src/github.com/RTL/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.16.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.16.2
gyp verb command install [ '8.16.2' ]
gyp verb install input version string "8.16.2"
gyp verb install installing version: 8.16.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.16.2
gyp verb ensuring nodedir is created /root/.node-gyp/8.16.2
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.16.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/gocode/src/github.com/RTL/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '8.16.2' ]
gyp verb install input version string "8.16.2"
gyp verb install installing version: 8.16.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.16.2
gyp verb ensuring nodedir is created /opt/gocode/src/github.com/RTL/node_modules/node-sass/.node-gyp/8.16.2
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.16.2' ]
gyp verb remove using node-gyp dir: /opt/gocode/src/github.com/RTL/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.16.2
gyp verb remove removing development files for version: 8.16.2
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.16.2' ]
gyp verb remove using node-gyp dir: /opt/gocode/src/github.com/RTL/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.16.2
gyp verb remove removing development files for version: 8.16.2
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/gocode/src/github.com/RTL/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-1062.1.2.el7.x86_64
gyp ERR! command "/usr/local/lib/nodejs/node-v8.16.2-linux-x64/bin/node" "/opt/gocode/src/github.com/RTL/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/gocode/src/github.com/RTL/node_modules/node-sass
gyp ERR! node -v v8.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN @angular/http@7.2.15 requires a peer of @angular/core@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@7.2.15 requires a peer of @angular/platform-browser@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-18T05_38_59_157Z-debug.log

**Comment by ShahanaFarooqui** [comment]
@babaiants please try to install with unsafe-perm flag (npm install --unsafe-perm) and ensure to run the command as an administrator.

**Comment by babaiants** [comment]
Thanks, it worked that way
_npm install -g --unsafe-perm_
