### ISSUE TITLE
"Cannot validate certificate for 127.0.0.1 because it doesn't contain any ip Sans" error

### ISSUE THREAD

**Issue by plantOS** [ShahanaFarooqui/RTL#20]
**Description**
Despite correct password input which is the same for 'lncli unlock', receive error "Cannot validate certificate for 127.0.0.1 because it doesn't contain any ip Sans". LND and Bitcoind is running well without issues.

**To Reproduce**
1. After input password on web interface
2. "Cannot validate certificate for 127.0.0.1 because it doesn't contain any ip Sans" error is received
3. When 'lncli unlock' entered with correct password
4. "Please Check Server Connection" error is received

**Screenshots**
https://i.ibb.co/4YgqnDg/image.png
https://i.ibb.co/6w4mMgq/Selection-162.png

**Your environment**
* LND - version 0.5.1-beta commit=v0.5.1-beta-252 ge6623f98b38f279900aaedf6a6993f34c3a45337
* Ubuntu - 16.04
* Bitcoind - v0.17.0.0-ge1ed37edaedc85b8c3468bd9a726046344036243

@ShahanaFarooqui @saubyk Please help

**Comment by saubyk** [comment]
Hi, trying to understand your issue better.
Are you able to login to the app, but not able to unlock LND?

We have not updated our LND nodes to 0.5.1 yet...so cannot be certain. Below are my recommendations:
- Make sure you have the latest update of RTL build.
- Stop LND. Delete the TLS certs of LND. Restart LND again to re-generate the certs.
- Try login from RTL again.

Let us know if the above works. Thanks.

**Comment by plantOS** [comment]
Thanks we appreciate that. Yes was able to login to the app but not unlock LND. After re-generating TLS certs by deleting tls.cert and tls.key in ~/.lnd it works now with latest RTL code on mainnet.

```
commit 5af8176f8ca32817983cf45053ca59efb78e5b76
Date:   Wed Jan 2 19:57:05 2019 -0500
```
