### ISSUE TITLE
Anyone have any insights on getting RTL to wait for lnd and start after? here is my conf:

### ISSUE THREAD

**Issue by rbuckhoy** [ShahanaFarooqui/RTL#22]
Error:

● RTL.service - RTL daemon
   Loaded: loaded (/etc/systemd/system/RTL.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-01-03 20:49:32 EST; 17s ago
  Process: 1231 ExecStart=/usr/bin/node /home/admin/RTL/rtl (code=exited, status=203/EXEC)
 Main PID: 1231 (code=exited, status=203/EXEC)

Cant seem to get the daemon to start on reboot. here is my conf:

# Raspibolt RTL: systemd unit for RTL
# /etc/systemd/system/RTL.service

[Unit]
Description=RTL daemon
Wants=lnd.service
After=lnd.service

[Service]
ExecStart=/usr/bin/node /home/admin/RTL/rtl
User=admin
Restart=always
TimeoutSec=120
RestartSec=30

[Install]
WantedBy=multi-user.target

**Comment by saubyk** [comment]
Hi, please ensure that RTL.conf file is created in the RTL folder.
This change has been made recently to add user authentication in the application.

Please go over readme file for the contents of the RTL.conf file. Thanks.

**Comment by rbuckhoy** [comment]
Yes. I'm running the new version with the proper .conf file. I have a quick fix going for now with the screen command. I think it may have more to do with my systemd service of RTL some way.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saubyk** [comment]
Thanks for the update. Closing this issue now.
