### ISSUE TITLE
On-chain transactions list

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#26]
**Describe the solution you'd like**
Two sub-menus to be created under 'LND Wallet':
1. 'Send/Receive' - The current functions under 'LND Wallet' should be moved under 'Send/Receive' sub-menu.
2. 'List Transactions' - This menu should list the on-chain transactions done with the node's LND wallet. REST API for list transactions - "GET /v1/transactions".

**Comment by ShahanaFarooqui** [comment]
Done in 0.1.9-alpha
