### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by SatNakDJT** [ShahanaFarooqui/RTL#28]
I was following this guide (https://github.com/ShahanaFarooqui/RTL/blob/master/README.md) to install RTL, but when I got to the "npm install" step, I got this:

(node:10781) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/admin/RTL
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/admin/RTL/npm-debug.log
npm ERR! not ok code 0

Does anyone know what is wrong?

Thanks.

**Comment by saubyk** [comment]
Hi,

Looks like you have an outdated version of npm.

Can you upgrade your npm to the latest and then try?

Also, whats the os on which your running your node?

**Comment by SatNakDJT** [comment]
I actually didn't even npm at all before and just installed it prior to the error I reported with sudo apt-get install npm, so I don't think it is outdated, unless I should have installed it differently.

The OS is raspbian. I've got bitcoin and LND node on a pi via stadicus' guide.

**Comment by SatNakDJT** [comment]
Thank you, the link to the comment you provided updated npm from 1.4.21 to 6.5.0. I am surprised that 'sudo apt-get install npm' doesn't install the latest version.

With the updated version, the installation was successful! Thanks.

**Comment by saubyk** [comment]
Thanks for the update. Closing the issue.
