### ISSUE TITLE
Peer can be connected with just the public key

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#3]
**Is your feature request related to a problem? Please describe.**
Connecting to a Peer with a public key, need not require a IP address and port. It can be done with just the public key.

**Describe the solution you'd like**
A complete connection string can be constructed with just the public key. The GetNodeInfo(REST API - /v1/graph/node) function can be used to fetch the IP address and port, which can then be used to construct a connection string, which can be passed to connect function to connect with the peer.

**Comment by ShahanaFarooqui** [comment]
Feature Added!!
