### ISSUE TITLE
Config settings errorfails to load due to config file error

### ISSUE THREAD

**Issue by tim222tim** [ShahanaFarooqui/RTL#31]
**Describe the bug**
RTL fails to load due to config file error

**To Reproduce**
After install, I run LND without first creating RTL.conf, and get:

```
Something went wrong, unable to create config file!TypeError: Cannot read property 'lndServerUrl' of undefined
Server is up and running, please open the UI at http://localhost:3000
```

I enter a password into the UI and crash with:

```
TypeError: Cannot read property 'nodeAuthType' of undefined
    at /home/tim/RTL/controllers/authenticate.js:20:57
```

Now RTL.conf has been created. If I run again, I get:

```
/home/tim/RTL/connect.js:44
  if(config.Authentication.lndServerUrl === '' ||  undefined === config.Authentication.lndServerUrl) {
                           ^
TypeError: Cannot read property 'lndServerUrl' of undefined
```

The config file does contain the setting lndServerUrl. I've tried many different combinations of various config settings and have been unable to get RTL to execute no matter what I put in RTL.conf.

**Your environment**
lnd 0.5.1-beta
Ubuntu 16.04.5 LTS
bitcoind 0.17.0

**Additional context**
I was able to run RTL about a month ago. I wiped it and did a new pull and started having this issue.

**Comment by saubyk** [comment]
Hi, can you please post your RTL.conf settings (you can mask the password value if you have it in).

**Comment by tim222tim** [comment]
Here's what I have now:

```
[authentication]
lndServerUrl=https://localhost:8080/v1
macroonPath=~/.lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
lndConfigPath=~/.lnd/lnd.conf
rtlPass=dummy

[settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
```

In this configuration, I get the error:

```
/home/tim/RTL/connect.js:33
    if(config.Authentication.macroonPath !== '') {
                             ^
TypeError: Cannot read property 'macroonPath' of undefined
```

**Comment by saubyk** [comment]
For macroonPath and lndConfigPath please provide the complete path, not relative paths...

E.g. /home/admin/.lnd/data/chain/bitcoin/mainnet

**Comment by tim222tim** [comment]
Thanks. I did try that the other day. I just tried it again now. Here's my config:

```
[authentication]
lndServerUrl=https://localhost:8080/v1
macroonPath=/home/tim/.lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
lndConfigPath=/home/tim/.lnd/lnd.conf
rtlPass=dummy

[settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
```

And here are the results:

```
/home/tim/RTL/connect.js:33
    if(config.Authentication.macroonPath !== '') {
                             ^
TypeError: Cannot read property 'macroonPath' of undefined
```

**Comment by saubyk** [comment]
Try changing the section headers to:
[Athentication] and [Settings]

Or copy the section headers from the sample RTL.conf file on the repo.

**Comment by tim222tim** [comment]
Bingo!

Dang, I should have tried copying the sample from the repo. It seems that the default config that gets written out has bad headings.

Looks like I'm working now. Thanks!

-- Tim

**Comment by saubyk** [comment]
Thanks for the update. Closing this issue now.

**Comment by ShahanaFarooqui** [comment]
@tim222tim, apologies for the confusion. We fixed the issue in the code also. New rtl.config file will write titles in camel case now.

**Comment by tim222tim** [comment]
Thanks for your help. I look forward to using RTL.
