### ISSUE TITLE
Mainnet (blue) running instead of Testnet (green)

### ISSUE THREAD

**Issue by rbuckhoy** [ShahanaFarooqui/RTL#34]
Mainnet running instead of testnet? My setup runs perfectly but lately I can't get it to load green testnet. It's starts green and goes blue. 

RTL.conf: 

[Authentication]
lndServerUrl=https://localhost:8080/v1
macroonPath=/home/admin/.lnd/data/chain/bitcoin/testnet
nodeAuthType=CUSTOM
lndConfigPath=/home/admin/.lnd/lnd.conf
rtlPass=******
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false

**Comment by ShahanaFarooqui** [comment]
@rbuckhoy, Skin colors are not associated with LND instances. It is completely independent and unrelated to LND instances.

The skin color can be changed by clicking on the rotating setting icon on the right and making a choice from the 6 available options.

There is a default setting in RTL, which is overwritten by the information obtained from the LND instance to which RTL is connecting. This is the reason you might see a brief change over from green to blue, when you connect RTL with LND.

The information about LND instance can be confirmed from Top of RTL menu and dropdown menu.
![image](https://user-images.githubusercontent.com/23240721/51076318-14eb8c80-1665-11e9-9062-c19ca2ec7253.png)

There is no configuration to change mainnet to testnet from RTL. That is driven by LND to which RTL is connected.

**Comment by rbuckhoy** [comment]
I was afraid youd say that.....so im stumped as to why it worked for a while and stopped.

**Comment by saubyk** [comment]
Please pull the latest update. We've made the default skin as blue and removed the default chain type parameter.
Let us know if you still have more queries about this.
Thanks.
