### ISSUE TITLE
Update Channel Policy

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#39]
**Describe the solution you'd like**
Ability to update channel policy to adjust base_fee_msat, fee_rate, time_lock_delta at channel level or for all channels on the node.

API:
/v1/chanpolicy

The channel policy can be updated on the 'Management' list page. The update can be for each channel row, or all channels can be updated from the header row.
The input required for updating channels would be:
base_fee_msat
fee_rate
time_lock_delta
and chan_point (optional)
Upon clicking the control for updating the channel policy, a modal should be opened with the required fields to be input by the user. In case a channel is getting edited at the row level, the current values should also be populated in the modal. These values can be edited by the user.

For mass update, no initial values should be populated in the fields.

**Comment by ShahanaFarooqui** [comment]
Done.
