### ISSUE TITLE
Improve Security in Local Network

### ISSUE THREAD

**Issue by rootzoll** [ShahanaFarooqui/RTL#4]
**Is your feature request related to a problem? Please describe.**
When RTL is activated on the RaspiBlitz and the wallet gets locked from one computers browser. Every other computer on the local network can control/manage the node, without any security check. Its not highly critical, but when people running mainnet they may prefer a bit more security. 

**Describe the solution you'd like**
The browser and the nodejs server should establish some kind of session. That people even can even logout from.

**Describe alternatives you've considered**
As a quickfix - without further RaspiBlitz integration - one solution could be that the server remembers the local IP from the browser that unlocked the wallet and tells every other computer calling the side first to lock the wallet again from there before it can be unlocked on another or even offering a lock and unlock option.

**Additional context**
Later on with a deeper RaspiBlitz integration we can use Password D of the user for making a login to the RTL webinterface and then the browser remembers a session the user can logout from or something like that. 

Good work so far .. just an idea for the coming future :)

**Comment by saubyk** [comment]
Thanks @rootzoll . This is a great suggestion. I have included it in the roadmap.
https://github.com/ShahanaFarooqui/RTL/blob/master/Roadmap.md

We have not kept it at high priority right now, as RTL is operating on the LAN.
Once we have the basic feature set built out, we will focus on implementing an application level authentication in RTL.
