### ISSUE TITLE
RTL User session management

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#40]
Any user requiring access to RTL, needs to be authenticated. 
Refer to issue (https://github.com/ShahanaFarooqui/RTLFullApplication/issues/2) for details on authentication options.
Documenting the user session management scenarios covered with RTL.

1. User Idle time - User idle time is set for one hour (no configuration at this point). If the session is idle for more than one hour, the user will be logged out

2. Closing browser tab/window - If the user closes browser tab or window, the active session will be in-authenticated and user will be logged out, unconditionally. Any new session initiated needs to be authenticated again.

3. User activity - As long as the user is active on the application and the intermediate session inactivity period is not exceeded by one hour, the session will remain authenticated and the user will not be required to login.

**Comment by ShahanaFarooqui** [comment]
Done.
