### ISSUE TITLE
Show country/location on peers

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ShahanaFarooqui/RTL#42]
Show country/location on peers.

**Comment by saubyk** [comment]
@walterkok
This feature requires use of apis for tracking the geolocation.
We were unable to find any free public apis to be able to leverage and provide this feature.
All of the APIs we found required registration, which we cannot provide for a decentralized app like RTL.

This feature cannot be developed without any such free and public apis, hence closing this issue.
