### ISSUE TITLE
RTL unable to unlock Lnd wallet

### ISSUE THREAD

**Issue by Jeroensbel** [ShahanaFarooqui/RTL#45]
Hi, this is my first issue posted on Git, so forgive my process.

Bitcoin Core node running
Lnd node running, wallet locked
Node RTL server running
127.0.0.1:3000 page is loaded
logged into RTL
Unlock Lnd Wallet > ERROR > Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!
RTL.log > Wallet: 20: 1549468724944: INFO: Unlock Wallet Response: undefined

RTL.conf:
[Authentication]
lndServerUrl=https://127.0.0.1:8080/v1
macroonPath=C:\Users\user\AppData\Local\Lnd\data\chain\bitcoin\mainnet
nodeAuthType=CUSTOM
lndConfigPath=C:\Users\user\AppData\Local\Lnd
rtlPass=******
enableLogging=true
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false

Lnd.conf:
datadir=C:\Users\user\AppData\Local\Lnd\data
logdir=C:\Users\user\AppData\Local\Lnd\logs
maxlogfiles=3
maxlogfilesize=10
tlscertpath=C:\Users\user\AppData\Local\Lnd\tls.cert
tlskeypath=C:\Users\user\AppData\Local\Lnd\tls.key
tlsextraip=0.0.0.0
adminmacaroonpath=C:\Users\user\AppData\Local\Lnd\data\chain\bitcoin\mainnet\admin.macaroon
debuglevel=info
listen=0.0.0.0:9735
## listen=[::1]:9736
externalip=0.0.0.0
rpclisten=127.0.0.1:10009
restlisten=127.0.0.1:10010
nat=false
alias=Flipping_A_BitCoin
color=#ffaa00
maxpendingchannels=10
bitcoin.mainnet=1
bitcoind.dir=C:\Program Files\Bitcoin\daemon\bitcoind.exe
bitcoin.defaultchanconfs=3
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.2
#bitcoind.rpcpass=*******
lnddir=C:\Users\user\AppData\Local\Lnd
bitcoin.active=1
bitcoin.node=bitcoind
bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=******
#bitcoind.rpcpass=*******
bitcoind.rpcpass=************************************************
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501

For some reason the servers are not talking to eachother.

Lnd=lnd-windows-amd64-v0.5.2-beta-rc7
RTL=0.1.14-alpha
Bitcoin Core=v0.17.1
Os=Windows 10

My suspicion is an issue with the use of the .cookie for rpcauth but without the use of the .cookie the Lnd node shuts down.

If in need of more info, please ask.

Kind regards
Jeroensbel

**Comment by saubyk** [comment]
Most probably, your issue can be fixed by changing your lnd.conf file.
I took the content you posted and re-formatted the file. You can try with the below.
After updating the lnd.conf file, stop lnd and start it again.

[Application Options]
datadir=C:\Users\user\AppData\Local\Lnd\data
logdir=C:\Users\user\AppData\Local\Lnd\logs
maxlogfiles=3
maxlogfilesize=10
tlscertpath=C:\Users\user\AppData\Local\Lnd\tls.cert
tlskeypath=C:\Users\user\AppData\Local\Lnd\tls.key
adminmacaroonpath=C:\Users\user\AppData\Local\Lnd\data\chain\bitcoin\mainnet\admin.macaroon
debuglevel=info
alias=Flipping_A_BitCoin
color=#ffaa00
maxpendingchannels=10

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.defaultchanconfs=3

[Bitcoind]
bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=******
bitcoind.rpcpass=******
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.2

**Comment by Jeroensbel** [comment]
Thanks for restructuring the lnd.conf, I used it as an example but the problem remains.

ERROR
Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!

**Comment by ShahanaFarooqui** [comment]
The REST API invocations from the applications are failing for some reason. We are not able to see the failure reason from the log.
If you have recently upgraded LND from a lower version to 0.5.2
Please try this once:
1. Stop LND
2. Delete tls.cert and tls.key file
3. Restart LND and Unlock from the command line
4. Retry RTL

**Comment by ShahanaFarooqui** [comment]
Also, please confirm if your LND is completely synced with Bitcoind or not?
Run `lncli getinfo` from the command line and verify the value of "synced_to_chain".

**Comment by Jeroensbel** [comment]
When I delete the tls cert & key files, Lnd shuts down
2019-02-07 09:48:32.940 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta-rc7, build=production, logging=default
2019-02-07 09:48:32.941 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-02-07 09:48:32.951 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2019-02-07 09:48:32.963 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2019-02-07 09:48:32.963 [INF] RPCS: password gRPC proxy started at 127.0.0.1:10010
2019-02-07 09:48:32.964 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2019-02-07 09:49:25.752 [INF] LNWL: Opened wallet
2019-02-07 09:49:25.835 [INF] LTND: Primary chain is set to: bitcoin
unable to create chain control: unable to connect to bitcoind: status code: 401, response: ""
2019-02-07 09:49:26.104 [INF] LTND: Shutdown complete
unable to connect to bitcoind: status code: 401, response: ""

Yes, LND is fully synced_to_chain and was updated to 0.5.2 RCv7 2 days ago.

**Comment by ShahanaFarooqui** [comment]
Does your bitcoin.conf have the entries for rpc?

**Comment by Jeroensbel** [comment]
The rps passw is generated by this script: https://github.com/bitcoin/bitcoin/tree/master/share/rpcauth
My rpcuser has no special characters.

**Comment by saubyk** [comment]
We need to get LND working with Bitcoind first, before moving to the next step of running RTL.
Can you please confirm, if your LND is connecting with Bitcoind?
If not, I would recommend getting on the LND slack channels to seek help on that.

Your tls cert and key should have been generated again, once you restarted LND. Problem appears to be something else.

**Comment by Jeroensbel** [comment]
Yes, Lnd runs correctly with Bitcoind and the new tls cert & key are being generated.
The Lnd wallet opens fine when I use lncli.exe unlock.
It is also synced as they both run already for months together. I have the same setup running on multiple machines and none of them can open the Lnd wallet through RTL.
As mentioned above it looks like with the new Lnd version the REST API invocations from the applications are failing for some reason. And there is no log info on what it can be.
It looks to me that RTL can not use the rpcauth in the Lnd.conf for rpc authorisation. 
But I am not knowledgeable/skilled enough to judge this.

**Comment by saubyk** [comment]
Can you please try to run https://localhost:8080/v1/getinfo in postman and confirm if you are getting a valid response?
If LND is able to talk to Bitcoind, than you don't need to worry about how rpc user/password is stored in the conf file. Although in this case we would recommend to use CUSTOM authtype in RTL.conf.

**Comment by Jeroensbel** [comment]
Could not get any response
There was an error connecting to https://localhost:8080/v1/getinfo.

Yes, authtype is set to CUSTOM in RTL.conf otherwise it would not log me in.

**Comment by saubyk** [comment]
Can you please provide the error description that you are getting while connect to getinfo API.

**Comment by Jeroensbel** [comment]
Could not get any response
There was an error connecting to https://localhost:8080/v1/getinfo.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**Comment by ShahanaFarooqui** [comment]
Hi, are you passing the macaroon in the header? Try with the below:
You would need to create a key-value pair in the header
Key: Grpc-Metadata-macaroon
Value: <Macroon text converted to a hex string>

**Comment by Jeroensbel** [comment]
same result
![image](https://user-images.githubusercontent.com/47392432/52543824-5182e300-2ddf-11e9-8f9c-aa70904117e7.png)

**Comment by saubyk** [comment]
The rest api needs to work for RTL to function. Not able to figure the exact reason why APIs are failing in your case.
Try removing all the extraneous variables from your lnd.conf file like tlscertpath, tlskeypath, macaroonfilepath etc. and restarting LND.

**Comment by Jeroensbel** [comment]
Thanks, I removed everything extraneous but this changed nothing.
BUT, I was wondering which restlistenport RTL was quereing so I choose to remove the port in Lnd.conf altogether and that worked.
restlisten=127.0.0.1

TY for the assistance.

**Comment by ShahanaFarooqui** [comment]
@Jeroensbel We receive this response from LND while trying to unlock but it still unlock the wallet also. So, even with this error response, you will be able to manage your node with RTL. We are closing this ticket now.
