### ISSUE TITLE
Unable to commit all funds without change address

### ISSUE THREAD

**Issue by seth586** [ShahanaFarooqui/RTL#46]
I have 498,519 satoshis left in my wallet. I would like to commit all funds so I do not have a change address.  (dust UTXOs are bad!) Right now its impossible to guess the correct funding amount to make this happen.

I would suggest allowing the user to type in 'max' in the `Amount (Sats) *` field that would commit all funds without a change address.

In the future, coin control would be nice. For example, Electrum handles this with a 'coins' tab, allowing you to spend specific UTXOs. This is also important when using privacy wallets such as wasabi.

**Comment by saubyk** [comment]
Hi, please note that we are just providing a UI on top of LND wallet functions, which are exposed via the REST APIs. We are not creating a new wallet per se, in RTL.
Unless LND provides these features on its wallet, we cannot extend the same functions via the UI.
Thanks.

**Comment by seth586** [comment]
Thanks!

**Comment by saubyk** [comment]
hi @seth586 
there is support in the SendCoins API now to send all the funds out of your wallet. We are planning to implement this feature soon. Please check the below issue:
https://github.com/ShahanaFarooqui/RTL/issues/66

**Comment by saubyk** [comment]
Unless you were referring to opening channels and not removing the funds from your LND wallet, in which case, that feature is still not available with the LND API. :-)
