### ISSUE TITLE
Include wallet setup in web ui

### ISSUE THREAD

**Issue by seth586** [ShahanaFarooqui/RTL#48]
I maintain a FreeNAS BTC/LN guide: https://github.com/seth586/guides/tree/master/FreeNAS

**Is your feature request related to a problem? Please describe.**
FreeNAS is working on a 'point and click' [bitcoin plugin](https://github.com/freenas/iocage-plugin-bitcoin-node). In the future I would like to make a lightning plugin, but the problem is the command line required to set up lnd's wallet.

**Describe the solution you'd like**
I would like to reduce the barrier to entry. Perhaps RTL could web-ui `lnd`'s initial wallet creation step, so a FreeNAS plugin could be deployed in a preconfigured state so the user can go straight to the UI without navigating the command line.

**Comment by seth586** [comment]
Disregard, I see this is on the [roadmap](https://github.com/ShahanaFarooqui/RTL/blob/master/Roadmap.md). Thanks for the UI, I love it!

**Comment by saubyk** [comment]
Thanks for the feedback. We'll look to prioritize your request. :-)
