### ISSUE TITLE
Scrolling function is not working correctly on the Channel screen

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#5]
**Describe the bug**
Not able to scroll through the channel list on the channel screen.

**To Reproduce**
1. Go to the Channels screen
2. Try scrolling on the channel list
3. If the number of records are 5+, the scrolling is erratic and not working properly

**Expected behavior**
The scroll function should work smoothly.

**Comment by ShahanaFarooqui** [comment]
Fixed
