### ISSUE TITLE
RTL stuck at 'Unlock' screen

### ISSUE THREAD

**Issue by vindard** [ShahanaFarooqui/RTL#52]
Pretty much, I've been getting the exact issue as the folks in Issues #43 & #45. Specifically, I can't seem to get past [this error](https://github.com/ShahanaFarooqui/RTL/issues/45#issuecomment-461256427).

I've already tried _literally all_ the suggestions in those two other issue threads to no avail.

# Configs

I've git cloned RTL into a linux machine and am trying to access remotely to my `lnd` instance running on an RPi3 on the local network:
```
{
    "identity_pubkey": "[redacted]",
    "alias": "[redacted]",
    "num_pending_channels": 0,
    "num_active_channels": 32,
    "num_peers": 34,
    "block_height": 563338,
    "block_hash": "00000000000000000027d588760026a00dd92c58550e71c8f1581225142c37bb",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "[redacted]"
    ],
    "best_header_timestamp": "1550354745",
    "version": "0.5.2-beta commit=v0.5.2-beta",
    "num_inactive_channels": 5
}
```

My RTL.conf file
---
```
[Authentication]
lndServerUrl=https://192.168.0.201:8080/v1
macroonPath=/home/arvinda/Desktop/lnd-node-files
nodeAuthType=CUSTOM
rtlPass=[redacted]
enableLogging=false
#lndConfigPath=/home/bitcoin/.lnd/lnd.conf
[Settings]
flgSidenavOpened=false
flgSidenavPinned=false
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
```

My lnd.conf file
---
Uncommenting everything under `[Bitcoind]` tag below made no difference. I already have all these settings in my `bitcoin.conf` file as well and have never needed them here, but tried including them anyway as part of my troubleshooting.

```
# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=info
maxpendingchannels=5
alias=[redacted]
color=#68F442
#listen=localhost
#nat=false

#[Tor]
#tor.active=true
#tor.v3=true

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

bitcoin.node=bitcoind

#[Bitcoind]
#bitcoind.rpcuser=[redacted]
#bitcoind.rpcpass=[redacted]
#bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
#bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[Application options]
minchansize=140000
#restlisten=localhost:8080
#restlisten=192.168.0.201:8080
rpclisten=0.0.0.0:10009

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6
```

Screenshot
---
![image](https://user-images.githubusercontent.com/17693119/52905770-5dbed400-3215-11e9-9eda-d1c9a0d092ae.png)

**Comment by saubyk** [comment]
@vindard
Please check if port # 8080 open on your rpi firewall.
And try with the below modified lnd.conf:

# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=info
maxpendingchannels=5
alias=[redacted]
color=#68F442
minchansize=140000
restlisten=192.168.0.201:8080
#listen=localhost
#nat=false

#[Tor]
#tor.active=true
#tor.v3=true

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=[redacted]
bitcoind.rpcpass=[redacted]
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6

**Comment by vindard** [comment]
**Ah, the problem was `rpclisten=0.0.0.0:10009`!** Now that that one line is gone RTL starts up perfectly.

> _Note: I also commented back out everything under the `[Bitcoind]` as I had it originally and it still worked great._
---
Hmm, that's less than ideal though since I would like to have the gRPC interface available for other apps I use.  **Any ideas around how we can have both `restlisten` and `rpclisten` enabled in the config file?**

It could be made as a separate open issue that someone works towards maybe...

**Comment by saubyk** [comment]
@vindard 
Both these setting should not conflict. If you need rpclisten, try with the below:
`rpclisten=127.0.0.1.10009`

We are able to run RTL in both local and remote settings with both the entries in the lnd.conf file.

**Comment by vindard** [comment]
It looks like it's some sort of bug with `lnd` itself ([#1567](https://github.com/lightningnetwork/lnd/issues/1567)).

I've tried messing around with various combinations of `restlisten` and `rpclisten` being alternatively/simultaneously enabled, with `localhost`/`0.0.0.0`/`127.0.0.1`/`localhost`/`192.168.0.201 (RPi IP)` being toggled as well. 

I haven't been able to find a workable combination as yet that allows both gRPC and REST to function at the same time but I think I'll just wait for `lnd` to work that out at some point in the future.

For reference, my setup is a **Raspberry Pi 3** running **Raspbian Stretch Lite** for the OS.

**Comment by saubyk** [comment]
You have a working config now, in case you want to run RTL.
Closing this issue now.
Feel free to open another, in case you run into any other issues or if you have any feedback from your experience on RTL. :-)
Thanks.

**Comment by vindard** [comment]
I've finally gotten both rpc and rest services working now together!

**My solution ([source](https://github.com/lightningnetwork/lnd/issues/1567#issuecomment-437665324))**:
- add `tlsextraip=0.0.0.0` to the `lnd.conf` file
- delete the `tls.cert` file
- restart `lnd`.

**Comment by vindard** [comment]
Funnily it's now almost 2 years later and I'm setting up RTL on a new node and I think I've run into some version of this problem again (was searching my problem and found this issue) :see_no_evil: 

- I can successfully `curl` the `v1/getinfo` endpoint using the `admin.macaroon` I have available for RTL so I don't think it's a REST api access issue, and
- the `lnd` wallet is already unlocked anyway

I'll mess around and see what I can figure out again  :thinking:

![image](https://user-images.githubusercontent.com/17693119/102793392-3a6c8f00-4380-11eb-8dff-6b3e37c776ea.png)

**Comment by ShahanaFarooqui** [comment]
@vindard Feel free to share your RTL-config.json to double check your configuration after masking critical information.

**Comment by vindard** [comment]
Ah I figured it out after I noticed this funny little log message
```
INFO: RTLConf => Selected Node Updated To: "Node 1"
Common Set Options Error:{"errno":-20,"syscall":"open","code":"ENOTDIR","path":"/home/rtl/.lnd/admin.macaroon/admin.macaroon"}
Common Update Selected Node Options Error:{"errno":-20,"syscall":"open","code":"ENOTDIR","path":"/home/rtl/.lnd/admin.macaroon/admin.macaroon"}
```

It turns out I had set the `macaroonPath` path value to point directly to the file instead of its parent dir.

As a sidenote though, is there a reason why the `macaroonPath` value wants the parent dir path but the `configPath` value wants the path to the file?
