### ISSUE TITLE
Can the front end use a relative path to the api endpoint?

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#56]
@JeffVandrewJr managed to add RTL to BTCPay in a working state.

However, there is [one last point](https://github.com/btcpayserver/btcpayserver-docker/pull/99#discussion_r258761964) bothering me.

We need to route, at nginx level, all requests from `/api` to the RTL container. But, we plan to use `/api` at btcpay level.
I guess this route is used by the front end. If so, would it be able to use a relative path instead?

Right now:
*  queries to `https://btcpay.example.com/rtl` are routed to `http://rtl_container`
* queries to `https://btcpay.example.com/api` are routed to `http://rtl_container/api`

I wished instead

* queries to `https://btcpay.example.com/rtl` are routed to `http://rtl_container`
* **queries to `https://btcpay.example.com/rtl/api` are routed to `http://rtl_container/api`**

For this to work,, you only need, on the front end, to use a relative path to get the route of the api.

**Comment by JeffVandrewJr** [comment]
@ShahanaFarooqui and @saubyk, If for some reason you're worried about the suggestion above breaking compatibility with nodl or your users running naked without reverse proxies (which I don't think it would), you could choose to use the relative paths only when the `REVERSE_PROXY` env variable is set to '1', since it's always set that way in the docker fragment I drew up.

Whichever way you think is easiest would work.

**Comment by NicolasDorier** [comment]
@JeffVandrewJr well, using a relative path means it has no impact on current users.
Current users will still use `/api` because it is relative to the `https://rtl.example.com/`

**Comment by ketominer** [comment]
after discussing it, the proposed change is ok for nodl too :)

**Comment by ShahanaFarooqui** [comment]
Done.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui not a big deal, but if you can do the same for css and images it would be great.

I wanted to route * `https://btcpay.example.com/rtl/btc` to `http://rtl_container` but it did not worked because the styles were looked to `https://btcpay.example.com/rtl/styles`.
Not a big deal, but if that is something simple to fix it would be cool.
