### ISSUE TITLE
Fix chronical ordering of payments

### ISSUE THREAD

**Issue by MaxHillebrand** [ShahanaFarooqui/RTL#57]
**Describe the bug**
The ordering in accordance to the creation date in both the `List Payments` and `Invoices` checks first the month, then the day. This leads to a wrong time line that is not correct. 

**To Reproduce**
1. Go to 'List Payments' and 'Invoices'
2. Click on 'Creation Date'
3. See that the dates are not in the correct time line order.

**Expected behavior**
When the arrow points up: 

> Jan/01
> Jan/31 
> Feb/01
> Feb/31

When the arrow points down:

> Feb/31
> Feb/01
> Jan/31
> Jan/01

**Actual behavior**
When the arrow points up: 

> Feb/01
> Feb/31
> Jan/01
> Jan/31

When the arrow points down:

> Jan/31
> Jan/01
> Feb/31
> Feb/01

**Your environment**
* version `lnd v0.5.1-beta`
* operating system `Armbian based on Ubuntu v18.04 LTS` 
* version `bitcoind v0.17.1`

**Comment by ShahanaFarooqui** [comment]
Fixed Chronological Ordering of date/time on payments, invoices, wallet, forwarding history in v 0.2.13.
