### ISSUE TITLE
[Question] Running RTL on another machine separate to LND?

### ISSUE THREAD

**Issue by saliehendricks** [ShahanaFarooqui/RTL#59]
Was wondering if it is possible to run RTL on my main dev machine and communicate with a running LND on a Raspberry?

How would RTL read/access the macaroon files?

Looking forward to getting going.

**Comment by saubyk** [comment]
Yes you can configure RTL to remotely connect with your LND instance running on your network.
Follow the below steps:
1. Assign a static IP address to your raspberry pi.
2. Transfer the `admin.macaroon` file from your pi to the device on which you want to run RTL.
3. Add the following param to your lnd.conf file under the [Application Options] section:
`restlisten=<ip address of your rpi>:8080`
4. Change the params in your RTL.conf file:
[Authentication]
macaroonPath=<Path of the admin.macaroon on the device running RTL>
nodeAuthType=CUSTOM
rtlPass=<password in plain text>

[Settings]
lndServerUrl=https://<ip address of your rpi>:8080/v1

**Comment by saliehendricks** [comment]
Thanks for the config @saubyk ! Will give it a try

**Comment by saubyk** [comment]
@saliehendricks Closing this issue now. Assuming you have been able to configure and run RTL remotely.
In case you face any issues, feel free to re-open.
Thanks.
