### ISSUE TITLE
Incorrect Currency Unit Toggle on Litecoin chain

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#6]
**Describe the bug**
On the Litecoin chain, the settings panel shows currency unit toggle as BTC.

**To Reproduce**
1. Run RTL on LND running on Litecoin
2. Click on settings
3. View the Currency unit toggle.

**Expected behavior**
When LND is running on Litecoin, the currency unit toggle should show LTC.

**Your environment**
* version of `lnd` - 0.5
* operating system - raspabian
* version of `litecoind v 0.16.3`

**Comment by ShahanaFarooqui** [comment]
Fixed
