### ISSUE TITLE
[Feature Request] Sweep LND wallet

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#66]
I wish to remove all on-chain funds from my wallet without change. There is not easy way to do this.

**Comment by saubyk** [comment]
@NicolasDorier agreed.
Will make the change for this by utilizing the `send_all` parameter of the SendCoins API (POST /v1/transactions).
User will be able to make a selection in the UI by checking a flag ('Send all coins') and then amount entered will be greyed out or ignored and API will be invoked to send out all the funds.

**Comment by seth586** [comment]
Excellent, this will be a great way to consolidate UTXOs within the LND wallet as well!

**Comment by ShahanaFarooqui** [comment]
Feature added with release 0.2.14-beta
