### ISSUE TITLE
Target confirmation block and fee rate?

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#67]
![image](https://user-images.githubusercontent.com/3020646/53420595-6b4b3980-3a1f-11e9-9141-6fad09c6117b.png)

You are showing both: target block confirmation and the fee rate to use for the on chain transaction.

Why? What happen if both value are different? `target block confirmation` and `fee rate` are two different term for tweaking the same parameter.

**Comment by saubyk** [comment]
@NicolasDorier agreed.
We will make the change to allow the user to select either of the two, but not both.

**Comment by ShahanaFarooqui** [comment]
Feature added with release 0.2.14-beta
