### ISSUE TITLE
Problem with the rpc password

### ISSUE THREAD

**Issue by babonet13** [ShahanaFarooqui/RTL#68]
I'm running bitcoind : Bitcoin Core Daemon version v0.17.1
and lnd : lncli version 0.5.2-99-beta

I just successfully installed RTL on my "naka-dev" ubuntu box ...
... and i could successfully access to the RTL web interface from my Mac box (http://192.168.1.223:3000/rtl/login)

In the  RTL.conf file, I have choose : nodeAuthType=DEFAULT

But I could not connect to the RTL Web Interface using my RPC user password
(which is defined in my bitcoin.conf file)

My lnd.conf file just have a section like this : 
==============
[Bitcoind]
bitcoind.dir=/home/satoshi/.bitcoin/bitcoin.conf
===============

Thanks for help

**Comment by ShahanaFarooqui** [comment]
Please check below settings from your .conf files for RTL to be able to authenticate you through your RPC password:

A) RTL.conf:
- RTL SSO should be '0'. 
        [SSO]
        rtlSSO=0

- nodeAuthType should be set to 'DEFAULT'.

- lndConfigPath should be full path of the lnd.conf file including the file name.

        [Authentication]
        nodeAuthType=DEFAULT
        lndConfigPath=..............\lnd.conf

B) lnd.conf:

- bitcoind.rpcpass should be set under Bitcoind heading:

        [Bitcoind]
        bitcoind.rpcpass=xyz


But, even after above setting, if authentication fails, then:

a: Either authenticate with your custom RTL password. To do that, change your nodeAuthType to 'CUSTOM' and set 'rtlPass' in your rtl.conf.

b: Or, most probably, your lnd.conf needs to be refactored according to LND's specifications. You can refer there sample-lnd.conf for more details from 'https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf'.

**Comment by babonet13** [comment]
I have add the RPC password directly in bitcoind ...
... and I could log into the RTL web interface

Many thanks for you quick and efficient support !

**Comment by ShahanaFarooqui** [comment]
Happy to help and to know that it worked for you :). Closing the ticket now.

**Comment by tzarebczan** [comment]
For anyone else running into this, my heading was [bitcoind] instead of [Bitcoind] and it failed to pick it up (I must have mucked around with this manually at some point).
