### ISSUE TITLE
Problem with opening a channel

### ISSUE THREAD

**Issue by babonet13** [ShahanaFarooqui/RTL#69]
While trying to openning a chanel with yalls.org
Pub Key = 03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56

I got a first error message (because amount is not enough)

![capture d ecran 2019-02-27 a 15 34 08](https://user-images.githubusercontent.com/20139338/53497928-90828b00-3aa5-11e9-8522-8b042ddd1b60.png)

Then a second error message even if the Amount is OK (20000)

![capture d ecran 2019-02-27 a 15 34 44](https://user-images.githubusercontent.com/20139338/53498005-bdcf3900-3aa5-11e9-813e-052c35373d36.png)

What is the problem ?

**Comment by saubyk** [comment]
Hi, it appears that you are no longer connected with the peer.
Please hit refesh and ensure you are connected with the peer.

**Comment by babonet13** [comment]
ok. you're right !
Will try again once yalls peer is reconnected

**Comment by babonet13** [comment]
This time the peer is connetced and I got another error 

![capture d ecran 2019-02-27 a 15 51 42](https://user-images.githubusercontent.com/20139338/53498959-aa24d200-3aa7-11e9-8136-885628871465.png)

Whaoouu : this mean I need to put 0.04 BTC in this channel !?

**Comment by saubyk** [comment]
That might be a limit imposed by yalls to ensure that its not overwhelmed by too many small channels.

In general creating smaller sized channels is inefficient.

You can try opening channels with some other peer.

**Comment by babonet13** [comment]
Is there any interesting peers to be connected with ?
Can I connect with your peer ?

**Comment by babonet13** [comment]
Which amount do you recommend to put in a channel ?

**Comment by babonet13** [comment]
In the "Pending Channels" tab (http://192.168.1.223:3000/rtl/chnlpending) ...
... it could be useful to see the alias of the peer.

**Comment by babonet13** [comment]
Is there a place to see the total amount engaged in all channels ?

**Comment by saubyk** [comment]
You can view the total channel balance on the home page.

You can also view the local and remote balances aggregated on the home page

**Comment by saubyk** [comment]
Hope your queries are addressed. Feel free to open another, in case you face any other issue.
Closing this ticket now. Thanks.
