### ISSUE TITLE
Currency unit toggle on Litecoin chain does not work

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#7]
**Describe the bug**
The currency unit toggle does not shift the unit from Liteoshi to LTC

**To Reproduce**
1. Go to Settings
2. Click on Currency Unit toggle to shift the currency unit
3. The units does not change on the screen

**Expected behavior**
When the currency unit is toggled the unit on the screen should change per the selection.

**Your environment**
* version of `lnd 0.50`
* operating system `raspabian`
* version of `litecoind v 0.16.3`

**Comment by ShahanaFarooqui** [comment]
Fixed
