### ISSUE TITLE
[Feature Request] Use Camera as QR Scanner

### ISSUE THREAD

**Issue by JeffVandrewJr** [ShahanaFarooqui/RTL#71]
With Spark on mobile, the app asks for camera permissions, which it can then use for QR scanning. It would be cool if RTL could also do that.

**Comment by ShahanaFarooqui** [comment]
@JeffVandrewJr This feature can be best addressed via native mobile app. We don't have an easy way to do it with Angular and due to time scarcity, would prefer to spend it on other major issues. But, thanks for the suggestions and we will try to cover it whenever we can.
