### ISSUE TITLE
Sweep all bug: error:transaction output is dust

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#75]
![image](https://user-images.githubusercontent.com/3020646/53692680-95ae4580-3dd7-11e9-8f99-91ab4c3c5c8d.png)

I am unsure this is the problem of RTL. It might the problem of LND.
Dust outputs should be added to the fee.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier RTL is receiving this error message from LND API and only showing it on UI. This issue can be addressed by LND. Closing the issue now.

**Comment by NicolasDorier** [comment]
The problem is that sweep all is not supported on 0.5.2
