### ISSUE TITLE
[Feature Request] - Add optional params to Open Channel

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#76]
Add optional params for opening channel.
Following options can be provided to the user while opening channels:
1. Target Confirmation blocks / Sat per byte to customize channel opening fee/priority
2. 'Spend Unconfirmed Output' option to allow for unconfirmed outputs available in the wallet to be used for funding opening of channel.

**Comment by ShahanaFarooqui** [comment]
Done.
