### ISSUE TITLE
npm install: node-sass/release...not found

### ISSUE THREAD

**Issue by robclark56** [ShahanaFarooqui/RTL#77]
**Describe the bug**
npm install encounters this problem

Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm-67_binding.node"

**To Reproduce**
root@CRM-Pi:/data/RTL# npm install

> node-sass@4.10.0 install /data/RTL/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm-67_binding.node":

HTTP error 404 Not Found

**Expected behavior**
Install with no errors.

**Actual behavior**
See above

**Your environment**
 uname -a
Linux CRM-Pi 3.10.20-ubnt-mtk #2 SMP PREEMPT Fri Sep 11 10:12:13 PDT 2015 armv7l GNU/Linux

COMMENT
https://github.com/sass/node-sass/releases indeed seems to have no releases for arm71 processors (i.e. raspberry-pi type hosts)

**Comment by ShahanaFarooqui** [comment]
@robclark56 what is your npm version? It appears that you are not using the latest version of npm. Please upgrade it and try again.

**Comment by robclark56** [comment]
root@CRM-Pi:~# npm -v
6.7.0

I only installed last night

**Comment by ShahanaFarooqui** [comment]
It seems to be some version conflict issue only. We are also running RTL on raspberry-pi without any installation issue. 
A) Option A:
Please delete 'package-lock.json' from RTL root.
Delete node_modules folder from RTL root.
Run npm install again. 

B) Option B:
If above solution doesn't work than you might have to downgrade your npm to some older version. Ours is working successfully with npm v6.5.0.

**Comment by robclark56** [comment]
I tried option A above. No success

So I then 
* completely started from scratch (re-installed debian 9, added git, npm, nodejs)
```
root@CRM-Pi:/data/downloads/RTLFullApplication/RTL# node -v
v10.15.2
root@CRM-Pi:/data/downloads/RTLFullApplication/RTL# npm -v
6.4.1
```
* Followed the instructions in https://github.com/ShahanaFarooqui/RTLFullApplication
```
root@CRM-Pi:/data/downloads/RTLFullApplication/RTL# npm install

> node-sass@4.10.0 install /data/downloads/RTLFullApplication/RTL/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm-64_binding.node":

HTTP error 404 Not Found
```

The issue is that install is looking for a 'linux-arm...' file in https://github.com/sass/node-sass ... but that repository does not seem to have any linux-arm* files.

```
root@CRM-Pi:/data/downloads/RTLFullApplication/RTL# uname -a
Linux CRM-Pi 3.10.20-ubnt-mtk #2 SMP PREEMPT Fri Sep 11 10:12:13 PDT 2015 armv7l GNU/Linux
root@CRM-Pi:/data/downloads/RTLFullApplication/RTL# uname -m
armv7l
```

I am a bit lost now how to proceed.

**Comment by saubyk** [comment]
Hi @robclark56 If your node h/w does not have support for sass, you can run RTL on a different device than the node. The computer should be on the same network as your node.

Please refer to the below issue, on how to configure RTL to run on a separate computer than your node:
https://github.com/ShahanaFarooqui/RTL/issues/59

Let us know, if this approach helps.

**Comment by robclark56** [comment]
Thanks for the reply .... but I was under the impression that RTL would run on a Raspberry Pi, and that implies arm processors.

From what I can see:
* RTL requires sass
* sass is not available on arm processors
* RTL can not run on a Raspberry Pi

Have I got this correct??

(BTW ... my plan was actually to run RTL on host A, and have it query the lnd node on Host B. But both host A and Host B have arm processors.)

**Comment by saubyk** [comment]
@robclark56 RTL does run on raspberry pi. In fact, I have my own node running the whole stack on rpi (Bitcoind+LND+RTL).
Will re-look at this issue one more time.

**Comment by saubyk** [comment]
Hi @robclark56 
The problem seems to be the OS you are running on raspberry pi. Looks like you are running a derivative of Ubuntu for pi, which is not supported by node-sass.

If you run raspbian OS on pi, you will be able to run RTL, without any issues.

We are running RTL on the below config:
Linux xxxxx 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

Closing this issue for now. Please feel free to re-open if your issue is not addressed with raspbian.
Thanks.

**Comment by robclark56** [comment]
Thanks for trying.

But is there any way for you to find which of these releases you are downloading on a Raspberry pi?

https://github.com/sass/node-sass/releases/

I can't see anything there for an arm processor.

What I will try to do is manually install the same one,

Thanks

Rob

**Comment by saubyk** [comment]
hi @robclark56 below is excerpt from the package-lock.json
'''
"node-sass": {
          "version": "4.10.0",
          "resolved": "https://registry.npmjs.org/node-sass/-/node-sass-4.10.0.tgz"

**Comment by pandeykumar** [comment]
I'm getting similar issue in pi while trying to update to raspiblitz 1.2 .  Getting the latest from master.
Lowered the version of npm  6.5.0 but still same issue.
Linux RaspiBlitz 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

logs---
Build failed with error code: 1
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-16T01_46_06_189Z-debug.log

**Comment by ShahanaFarooqui** [comment]
@pandeykumar and @robclark56, Hi, it is an open issue at sass/node-sass github at https://github.com/sass/node-sass/issues/2652. They are asking for the full error log, can you please copy the content of your log file here or directly at node-sass’s github? Thanks.

**Comment by ShahanaFarooqui** [comment]
@robclark56 & @pandeykumar, Till node-sass fixes the issue from their end, you can use RTL with attached downgraded dependencies. Please replace your RTL's package.json and package-lock.json with attached files and run npm install again.

[node-sass-temp-fix.zip](https://github.com/ShahanaFarooqui/RTL/files/3189580/node-sass-temp-fix.zip)

**Comment by ShahanaFarooqui** [comment]
The above attachment seems to get corrupted. So please ignore that attachment and follow below steps:
Delete your package-lock.json
Replace content from 'https://pastebin.com/h1e3EYm0' into your package.json.
run 'npm install'. Successfull installation will create a new package-lock.json for you.

**Comment by ShahanaFarooqui** [comment]
@robclark56 & @pandeykumar, Closing this issue as we are tracking it with Issue https://github.com/ShahanaFarooqui/RTL/issues/148
