### ISSUE TITLE
Channel pop-up close button UX confusion

### ISSUE THREAD

**Issue by pavlenex** [ShahanaFarooqui/RTL#78]
The pop-up button which appears when you click on the channel (Channel Management > Channel XYZ) has close word, which may lead some users into thinking they're closing the channel where instead they are just closing the window.

![screen shot 2019-03-05 at 16 31 40](https://user-images.githubusercontent.com/36959754/53816819-92949000-3f64-11e9-93a1-c108d01d7602.png)

**Comment by ShahanaFarooqui** [comment]
@pavlenex Fixed with v.0.2.15
