### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by badokun** [ShahanaFarooqui/RTL#79]
To increase adoption clear instructions on how to start up a docker image should be documented. There is some reference https://github.com/ShahanaFarooqui/RTL/issues/44 but would be helpful if it's made available on https://hub.docker.com/r/shahanafarooqui/rtl

Something along the lines of https://github.com/badokun/lightning-metrics/blob/master/docs/lightning_metrics.md

**Comment by saubyk** [comment]
Hi @badokun 
Would happily accept a documentation PR, if you are up for it?

Not able to allocate time for this, right now. If you need any assistance in putting the documentation together, let me know. Thanks.

**Comment by badokun** [comment]
Sure I'll take a look at this. Not sure about all the parameters that needs to be passed in though. Actually I thought I saw @NicolasDorier mention something about adding this to BTCPay server, so perhaps this work is already under way.

**Comment by saubyk** [comment]
Hi @badokun 
RTL is already integrated and available with BTCPayserver.

If you are referring to, create directions on running RTL on a docker setup outside of BTCPayserver, then that warrants a separate documentation.

If you meant about BTCPayserver only, then that’s already done and this issue can be closed.

**Comment by badokun** [comment]
Ah didnt know that. Okay let's close this issue then, thanks!
