### ISSUE TITLE
Incorrect total balances on channel dashboard for zero balances

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#8]
**Describe the bug**
On the channel dashboard, on the total channel panel, even if the channel balance is zero, the value is shown as 100 for remote balance and local balance.

**To Reproduce**
1. Ensure that channel balances are zero
2. Go to Channel Dashboard
3. View the Total Channel Balances Panel
4. Value for both remote balance and local balance is shown as 100

**Comment by ShahanaFarooqui** [comment]
Fixed
