### ISSUE TITLE
Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!

### ISSUE THREAD

**Issue by lunaticoin** [ShahanaFarooqui/RTL#80]
**Describe the bug**
After my RTL pass is accepted and I am required to introduce my LND wallet pass I get this answer: 
"Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!"

**Additional context**
I am Running the Node Launcher by Pierre Rochard

This is my lnd.conf:
```
# Auto-Generated Configuration File
# Node Launcher version 5.6.0

debuglevel=info
restlisten=127.0.0.1:8080
listen=127.0.0.1:9735
rpclisten=127.0.0.1:10009

alias=******
color=#4a4a4a

lnddir=C:\Users\****\AppData\Local\Lnd

bitcoin.active=1
bitcoin.node=bitcoind

bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=******
bitcoind.rpcpass=******
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500

bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501
```
Hope you can help :)
![Captura](https://user-images.githubusercontent.com/41878201/54060038-89712080-41fb-11e9-9052-e6fa796afbca.PNG)

**Comment by saubyk** [comment]
Tweaked the lnd.conf file a bit. Try with this:
```
[Application Options]
debuglevel=info
restlisten=127.0.0.1:8080
listen=127.0.0.1:9735
#rpclisten=127.0.0.1:10009
alias=******
color=#4a4a4a
lnddir=C:\Users\****\AppData\Local\Lnd

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=******
bitcoind.rpcpass=******
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501
```

**Comment by lunaticoin** [comment]
Just tried and same problem unlocking the wallet :/

**Comment by ShahanaFarooqui** [comment]
@lunaticoin Can you please try to connect directly to LND port first? It most probably is not the issue with RTL but LND setup. You can connect directly through Postman/curl. 

You can follow below steps to test with Postman:
1) Enter your lnd REST server address in request url, select GET request option.
2) Add request header key as 'Grpc-Metadata-macaroon' and value as your macaroon hex.
3) Click on 'Send' Button, it should return a response similar to below screenshot.
Once you are able to get the response from LND REST server, then only RTL will be able to show you the unlocked UI.

![image](https://user-images.githubusercontent.com/23240721/54068685-73745780-421d-11e9-9bc6-d5200259fe0c.png)

**Comment by lunaticoin** [comment]
How to get the Hex value and from what macaroon? I tried converting the admin.macaroon to hex and the answer was "Couldn't get any response". Is it the right Macaroon? This Hex is a very long string right? 

Sorry to play the noob here

**Comment by saubyk** [comment]
@lunaticoin 

Please checkout the last comment on the below issue:
https://github.com/ShahanaFarooqui/RTL/issues/52

**Comment by lunaticoin** [comment]
Done that and no effect yet. Same Impossibility to unlock. 

Here is how it is my lnd.conf now (i tried both commenting the rpclisten and without)

```
[Application Options]
debuglevel=info
restlisten=127.0.0.1:8080
listen=127.0.0.1:9735
#rpclisten=127.0.0.1:10009
alias=******
color=#4a4a4a
lnddir=C:\Users\user\AppData\Local\Lnd

tlsextraip=0.0.0.0

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=*******
bitcoind.rpcpass=*******
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501
```

**Comment by saubyk** [comment]
Did you try deleting the tls.cert and key and restarting LND?

Also, are you installing all the software on the same comp Or you have a lightning node remote?

Is your lnd synced?

**Comment by lunaticoin** [comment]
I deleted both cert and key and restarted the LND

I am running the Pierre Rochard Node Launcher in the very same computer I am running RTL

And LND fully synced.

**Comment by ShahanaFarooqui** [comment]
@lunaticoin 
Regarding your macaroon query:
Either you can use in-built functions of any programming language like javascript/python or you can encode it with available online tools (I am not sure about the security aspects of online conversion tools and would recommend to do that only if you are on testnet).

Assuming that you are on testnet, you can follow below steps to encode macaroon:
a) Go to link: http://www.convertstring.com/EncodeDecode/HexEncode
b) Paste your admin.macaroon file's content in the first box (almost 10 lines & 232 char long)
c) Click on 'Hex Encode'
d) Copy the hex encoded text from the other box (almost 490 char long).

![image](https://user-images.githubusercontent.com/23240721/54076195-c9c1b480-4276-11e9-85a6-1b55675b4b16.png)

But, all these steps are only to establish the fact that your node is unable to connect with LND REST server. This will not resolve the issue but help you to debug it faster. 

Something needs to be fixed between your cert, key and lnd.conf to resolve it and @saubyk is the better person to handle that :).

**Comment by saubyk** [comment]
@lunaticoin lets try with an edited lnd.conf one more time:
```
[Application Options]
debuglevel=info
#restlisten=127.0.0.1:8080
listen=127.0.0.1:9735
#rpclisten=127.0.0.1:10009
alias=******
color=#4a4a4a
lnddir=C:\Users\user\AppData\Local\Lnd
#tlsextraip=0.0.0.0
[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
[Bitcoind]
bitcoind.rpcuser=*******
bitcoind.rpcpass=*******
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501

Also, can you please confirm the version of LND you are running.

**Comment by saubyk** [comment]
Hi @lunaticoin 
Haven't heard back on this from you. Hope you are able to run RTL with the last recommendation.
Closing this issue now.

Feel free to re-open or open another one, if you still need help. Thanks.
