### ISSUE TITLE
Use default file paths for the operating system

### ISSUE THREAD

**Issue by PierreRochard** [ShahanaFarooqui/RTL#81]
**Is your feature request related to a problem? Please describe.**

User should not have to manually enter file paths when they are using the defaults

**Describe the solution you'd like**

Something like this: https://github.com/willcl-ark/lnd_grpc/blob/master/lnd_grpc/utilities.py#L7

**Comment by ShahanaFarooqui** [comment]
Done.

**Comment by PierreRochard** [comment]
Thank you!

**Comment by ShahanaFarooqui** [comment]
@PierreRochard Sorry, I didn't realize that you will also get the update :p. Thanks for this enhancement issue and looking forward to improve more with your future suggestions :).
