### ISSUE TITLE
Include link to view LND and Bitcoin debug files

### ISSUE THREAD

**Issue by pxsocs** [ShahanaFarooqui/RTL#84]
Include 2 links for realtime monitoring of debug.log for Bitcoin and lnd.log for Lightning. 

Both could actually be included in the bottom of the front page showing the latest messages (akin to `tail -f` command).

**Comment by saubyk** [comment]
Hi @pxsocs 
Your suggestion is interesting, but we are not planning to develop this feature for performance reasons. We feel that this feature can create performance overheads on low power devices, which people may unknowingly trigger.

Closing this issue now.
Feel free to open another one, in case you have other feedback or any issues on RTL.

**Comment by Pauciradiatus** [comment]
@saubyk How about an alternative solution that has hardly any impact on performance? Two download buttons to download the logs individually.
