### ISSUE TITLE
[Feature Request] - Routing Peers

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#88]
Add a page for 'Routing Peers', to provide a better view of the forwarding volume on the node.
The forwarding data from the forwarding history api can be analyzed to group the data into two broad categories:
Incoming Traffic and Outgoing Traffic
The 'Incoming Traffic' section will summarize the routing events by channel id and show the following:
Channel ID, Peer Alias, Count of Routing Events, Total Amount In in sats.

The 'Outgoing Traffic' section will summarize the routing events by channel id and show the following:
Channel ID, Peer Alias, Count of Routing Events, Total Amount Out in sats.

 The default view should summarize for a period of last 30 days from the current date.

![Routing Peers](https://user-images.githubusercontent.com/39208279/54655127-0f605780-4a97-11e9-8cd7-e55fbe40ea15.png)

**Comment by ShahanaFarooqui** [comment]
Done.
