### ISSUE TITLE
Connection with raspiblitz

### ISSUE THREAD

**Issue by amcitaly** [ShahanaFarooqui/RTL#89]
**Describe the bug**

Hello, could you help me, I did all but it seem the connection between my raspiblitz and the RTL is broken. I will post a pic
![lnd conf](https://user-images.githubusercontent.com/46417649/54727620-12cc0f80-4b79-11e9-8be0-04773a846d56.PNG)

![unlock wallet](https://user-images.githubusercontent.com/46417649/54727798-0d22f980-4b7a-11e9-9003-cfa73c72e82b.PNG)

 
Before ope the RTL web on cmd prompt just shows "Server is up and running..." then once i enter my password on the RTL is seem is working, but in fact after 10 minutes it still "unlocking" but there are no progress. Then on the cmd prompt appear all the error message that you see. I saw that the port 3000 is not indicated on my raspiblitz, maybe is this... can you tell me how to open it? Thank you

![raspiblitz screen](https://user-images.githubusercontent.com/46417649/54727753-c9c88b00-4b79-11e9-8133-17b61c063a2f.PNG)

**Comment by saubyk** [comment]
@amcitaly  Hi
Before we get into the actual troubleshooting, you seem to be installing RTL on a device other than Raspiblitz. Is that your preferred setup to run?

If not, you can actually use the Raspiblitz script to install RTL directly. Which will simply the setup for you.

In case you want to run RTL separately, I will followup with the solution for you.

**Comment by saubyk** [comment]
In case you need to run RTL on a separate device, you need to transfer the admin.macaroon file out of the Raspiblitz and store it locally on the computer on which you are running RTL.

For the detail of the config you need to setup, please refer to the below issue:
https://github.com/ShahanaFarooqui/RTL/issues/59

Let us know, if you face any further issues. Thanks.

**Comment by amcitaly** [comment]
Thank you Saubik, well I am try to look the RTL from my win machine. But if I can use the script in the Raspiblitz I prefer as it seem easier. Can you tell me how to do? Thx

**Comment by amcitaly** [comment]
ah sorry, understood, I have to create the systemd unit. Ok i go for it thank you @saubyk
