### ISSUE TITLE
Status Filter is not working on the Channel list

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#9]
**Describe the bug**
Status filter is not working for Channel list.

**To Reproduce**
1. Go to Management under Channels
2. Select 'Active' or 'Inactive' from the Status Filter.
3. Selection does not filter the channel list based on the status, the list is unaffected.

**Expected behavior**
Upon selection of the status filter, the list should be updated and only the channels with the selected filter should be in the list.

**Comment by ShahanaFarooqui** [comment]
Fixed
