### ISSUE TITLE
Unable to unlock LND Wallet with Node Launcher

### ISSUE THREAD

**Issue by owldock** [ShahanaFarooqui/RTL#91]
I can log into RTL but stuck at "Unlock LND Wallet" -- when I use the wallet password I get the following error message: 
`"Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!" `

_(this is my first ever support ticket, so I appreciate your patience and please let me know if I forgot to add anything.)_ 

I used Node Launcher to launch LND, which unlocks the LND wallet. LND appears to be working, logs running fine etc. 

RTL terminal window shows this message:

`Wallet: 20: 1553196050500: INFO: Unlock Wallet Response: undefined`

RTL Conf:

> [Authentication]
> macaroonPath=/Users/***/Library/Application Support/Lnd/
> nodeAuthType=CUSTOM
> lndConfigPath=/Users/***/Library/Application Support/Lnd/lnd.conf
> rtlPass=***
> 
> [Settings]
> flgSidenavOpened=true
> flgSidenavPinned=true
> menu=Vertical
> menuType=Regular
> theme=dark-blue
> satsToBTC=false
> bitcoindConfigPath=
> enableLogging=true
> port=3000
> lndServerUrl=https://localhost:8080/v1
> 
> [SSO]
> rtlSSO=0
> rtlCookiePath=/Users/***/RTL/cookies/auth.cookie
> logoutRedirectLink=/login
> 

LND conf:

> Auto-Generated Configuration File
> 
> Node Launcher version 5.0.3
> 
> debuglevel=info
> #restlisten=127.0.0.1:8080
> listen=127.0.0.1:9735
> #rpclisten=0.0.0.0:10009
> tlsextraip=192.168.8.169
> color=#f2ff1b
> alias=***

Error message: ![error](https://user-images.githubusercontent.com/48806964/54780004-19956980-4bef-11e9-8383-021d50142194.png)

RTL: ![RTL](https://user-images.githubusercontent.com/48806964/54780021-23b76800-4bef-11e9-90ef-4f55a664cd5b.png)

**Comment by saubyk** [comment]
Hi @mguttentag 
Can you please try with the following RTL release?
https://github.com/ShahanaFarooqui/RTL/releases/tag/v0.2.15

Please keep the lnd.conf and RTL.conf as we've discussed. And, let us know if you are able to login.

Thanks.

**Comment by saubyk** [comment]
@mguttentag additionally can you please let us know where the RTL.conf file is located on your comp.
And confirm the complete file name. Thanks.

**Comment by saubyk** [comment]
Hi @mguttentag 
Please try the below: 
1. Make these changes in your lnd.conf:
`restlisten=0.0.0.0:8080`
`rpclisten=0.0.0.0:10009`
`tlsextraip=0.0.0.0`
2. Stop lnd
3. Delete 'tsl.cert' and 'tls.key' files
4. Restart lnd

**Comment by mguttentag** [comment]
Hi @saubyk! Made those changes on my Mac (Mojave OS) and it unfortunately didn't solve it: BTC/LND/Node Launcher all working; I can get onto the RTL server and log in with the RTL password...but I'm still getting the same error unlocking the LND Wallet `Unlocking Wallet Failed! Verify That Lnd Is Running And The Wallet Is Locked!`

(RTL is also successfully up and running on my Raspiblitz, which is nice -- thanks and great work!)

**Comment by saubyk** [comment]
Hi @mguttentag 

Can you please run this command on your Mac, and share the output:
`netstat -- anp|grep lnd`

We want to examine, the ip:port combination on which the lnd server is listening.

**Comment by mguttentag** [comment]
When I run the command `netstat -- anp|grep lnd` I get no response -- just a spinning wheel, then a new blank command prompt. Is there another way to get that data?

**Comment by owldock** [comment]
Just updating to say that after discovering other issues w/LND (possibly db corruption but i'm not  sure), I started over and re-set up LND, RTL, Node Launcher etc, and it's all working great, so i'm closing this issue. Thanks!
