### ISSUE TITLE
[Feature Request] - Node URI QR code

### ISSUE THREAD

**Issue by seth586** [ShahanaFarooqui/RTL#93]
**Is your feature request related to a problem? Please describe.**
Adding mobile wallets to my LND node is not an easy process.

**Describe the solution you'd like**
https://github.com/LN-Zap/lndconnect generates a QR code with all the authentication data to easily connect to my node. Perhaps RTL could generate such a QR code as well.

**Comment by jochemin** [comment]
Agree, there is space behind logout button in the side bar. Also it would be interesting to show the URI in the home page. 
![image](https://user-images.githubusercontent.com/6348955/54993162-84fd8380-4fc1-11e9-9999-b838986ac226.png)

**Comment by seth586** [comment]
Sorry, I shouldn't have labeled this feature request as "URI", I'm more-so looking for a UI for lndconnect, which contains sensitive data and should be hidden by default. This would take data from `Node Config` and the macaroons to generate an lndconnect qr.

**Comment by saubyk** [comment]
@seth586 What's the objective of this feature request?
Are you trying to simplify the process for gaining access to RTL on a mobile device, by scanning a QR code from a desktop RTL instance?
Or
Are you requesting a UI for lndconnect?

Need more clarification to make progress on this.
We can provide a QR code to scan and open RTL on a mobile. But a UI for lndconnect is not on our roadmap.

**Comment by seth586** [comment]
Yeah, this may be outside the RTL roadmap. The idea is basically a UI for a lndconnect style QR code in RTL to pass remote connection credentials to mobile wallets. ZeusLN example [here](https://github.com/seth586/guides/blob/master/FreeNAS/wallets/zeusln.md) 

Big picture idea for RTL: Users running bitcoind/lnd without ever going to the command line. tor/bitcoind/lnd/RTL stacked together in a docker container, FreeNAS plugin, etc. On boot, RTL checks if tor is listening on control port 9051, if so create a hidden service for rest and grpc ports listed in lnd.conf. RTL then provides user a lndconnect style QR code to connect their mobile wallet. The QR code contains the onion address, port, and macaroon. A user scans this QR code with their mobile wallet, and now have remote access to their funds no matter the NAT. This requires no router or ddns configuration. Its about the easiest remote connection setup I can imagine. I wrote about this idea [here](https://medium.com/@seth586/neutrino-can-be-dangerous-so-lets-grow-bitcoins-immunity-with-a-bip-bolt-2135956f147)

**Comment by seth586** [comment]
This is a duplicate of #138

#138 explains and gives better context based on recent implementations on other projects.
