### ISSUE TITLE
RTL / ZAP mobile app issue

### ISSUE THREAD

**Issue by walterkok** [ShahanaFarooqui/RTL#94]
Hi guys, yesterday I installed the ZAP ios app :

https://github.com/Stadicus/guides/commit/fbe725e02d92b5ded86a38c8d119cc1ab77cd677

All works fine but than RTL UI no longer works. You can login but it than asks you to unlock the wallet ( is already unlocked) and stops there.

The issue seems to come from the changes to lnd.conf needed for ZAP mobile app:

   tlsextraip=192.168.0.0/24
   rpclisten=0.0.0.0:10009

Cause when I changed it back commenting these 2 lines out RTL was working fine again.

Any solution you see tonhve them both work at the same time?

Regards Walter

**Comment by saubyk** [comment]
Hi @walterkok 
Try this, after making the entries you need for Zap, delete the tls.cert and tls.key files and restart LND.
(Tls files will be regenerated once you start LND)
Try accessing RTL after that.

**Comment by walterkok** [comment]
Hi @saubyk unfortunately that does not work (also see email with more detail) when I remove the .cert the Zap app disconnects
They do work independently but not at the same time

**Comment by saubyk** [comment]
@walterkok 
We can try one work around and see if that can work.
Whats your setup like? Are you running your node and RTL Server on the same device?
Can you consider moving RTL server to a different computer than your node?

If you can, we may be able to run both RTL and Zap.

But this setup would require some more tweaks to your LND and RTL setup.

Please refer to the below document on how to run RTL Server remote from the LND node.
https://github.com/ShahanaFarooqui/RTL/blob/master/RTL_setups.md

**Comment by 3cl1ps** [comment]
Got the same issue after adding the line 
rpclisten=0.0.0.0:10009
to give access to desktop zap.
Deleting tls.* didn't make it better.

After starting rtl, it is stuck at calling getinfo line and the UI is showing the wallet unlock box even if the wallet is already unlocked.

using lnd 0.5.2 & rtl commit 0b6*db9 on the same server

**Comment by walterkok** [comment]
Ok i will try
Currently rtl node is on the Pi too

Does RTL node use same rpc port? Can LND not listen to two different ports ( i tried to change the zal port to other address but than lncli does not work at all)

**Comment by saubyk** [comment]
@walterkok RTL does not uses rpc to connect with LND it uses REST
The port for the two should be different.

**Comment by walterkok** [comment]
Which restport 8080?
I can try to add restlisten=8080 in LND.conf?

**Comment by saubyk** [comment]
Try with this...
'restlisten=0.0.0.0:8080'

You may need to delete your tls files once.

**Comment by saubyk** [comment]
@walterkok  @3cl1ps 
Here is the recommendation, which I tested and it worked.
1. add the following to your 'lnd.conf' file in the [Application Options] section:
`restlisten=0.0.0.0:8080`
`rpclisten=0.0.0.0:10009`
`tlsextraip=0.0.0.0`

2. Stop lnd

3. Delete tls.cert and tls.key files

4. Restart lnd

This should address your problem.

Let us know, if it still persists. Thanks.

**Comment by 3cl1ps** [comment]
working, didn't have to delete tls.*

**Comment by walterkok** [comment]
hi @saubyk this works indeed when I am on the same network also for me. Both the app and RTL, nice!
I had to remove tls files as I was accessing from outside my net on public IP. That is not working yet (if I remove tlsextraip=0.0.0.0 (so only have tlsextraip=externalipaddress, it does not work yet, ideas?

**Comment by saubyk** [comment]
Hi @walterkok

Can you please explain your setup a bit?

Like, how are you hosting lnd and RTL and from where are you trying to access?

**Comment by walterkok** [comment]
sure, i am Stadicus compliant :-), so full bitcoin/lnd node on the raspberry pi. Also the RTL node runs on the same pi. I can access my pi remotely, also RTL (portforward). 
ZAP also works remotely (tls certificate with the public up address of my router) and than portforward to the pi with the 10009 port). 
your setup works well now (RTL and ZAP mobile) when I am on my local network, it is just that ZAP does not connect anymore remotely (also tried to include two extraip addresses

**Comment by saubyk** [comment]
Hi @walterkok 
Please note, unless you are running RTL behind a web server serving RTL over https, its not recommended to access it from outside your local network.

I am not sure, what tweak to provide you for zap. If zap is dependent on grpc, you can run a `netstat -anp|grep lnd` and see if LND is listening on the ip+grpc port.

It's best to check with zap team about this.

Closing this issue now. Let us know, if you need any further assistance. Thanks.
