### ISSUE TITLE
config without lnd.conf

### ISSUE THREAD

**Issue by awb99** [ShahanaFarooqui/RTL#95]
I am using LTD without a config file. Basically I start LND via a dockerfile that is similar to the LND sample dockerfile. Which parameters do I have to put into an "dummy LND config file", so that RTL would start up? Or is there a way to pass parameters via command line startup?

For reference this is how I start LND:

```
exec lnd \
    --debuglevel=trace \
    --noseedbackup \
    --logdir="/data" \
    "--bitcoin.active" \
    "--bitcoin.mainnet" \
    "--bitcoin.node=bitcoind" \
    "--bitcoind.rpchost=bitcoind:8332" \
    "--bitcoind.rpcuser=$RPCUSER" \
    "--bitcoind.rpcpass=$RPCPASS" \
    "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332" \
    "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333" \
    "--rpclisten=localhost:10001" \
    "--rpclisten=lnd:10001" \
    "--restlisten=0.0.0.0:8089" \
    "--listen=0.0.0.0:10011" \
    "$@"
```

As a side note I think it might be better to have dockerfiles that can build directly from git; because the dockerfile you specifies already requires that you build it from within the RTL project. Luckily it is easy to do:

```
FROM node:10-alpine
RUN apk add --no-cache tini git gcc musl-dev
WORKDIR /RTL
# Grab and install the latest version of of btcd and all related dependencies.
RUN git clone https://github.com/ShahanaFarooqui/RTL.git . 
# COPY package.json /RTL/package.json
# COPY package-lock.json /RTL/package-lock.json
# Install dependencies
RUN npm install
COPY ./RTL.conf /RTL
EXPOSE 3000
ENTRYPOINT ["/sbin/tini", "-g", "--"]
CMD ["node", "rtl"]
```

**Comment by awb99** [comment]
I forgot to mention: You made a great project! Really happy that you did this frontend!

**Comment by saubyk** [comment]
Hi @awb99 
Please refer to the environment variables available with RTL at the below page:
https://github.com/ShahanaFarooqui/RTL/blob/master/Application_configurations

In your case, you should set the following params, for RTL to work:
- PORT
- LND_SERVER_URL
- MACAROON_PATH
- NODE_AUTH_TYPE (set this to CUSTOM)
And set the password in the RTL.conf file.

**Comment by awb99** [comment]
@saubyk Thanks for your help. I now can start RTL, and I get into the web ui, however
after I login  it gets stuck:
```
console: 
Calling getinfo from lnd server url: INFO: http://localhost:8089/v1/getinfo
```
I tested the url that it is requesting, and there is data coming back. But it seems to be
encrypted or binary, so I am not sure what it is doing.

This is my RTL.conf file:
```
[Authentication]
macaroonPath=/lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
rtlPass=regenschirm13

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=http://localhost:8089/v1
bitcoindConfigPath=
enableLogging=true
port=3000

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login
```
I started the app with "node rtl"

Any ideas?
I set enableLogging to true, hoping that it would log what is going on, but it seems not to show
anything.

My github repo is: https://github.com/forteco/fortuneCookies
It is a sample application where you can buy chinese fortune cookies via lightening network.
It should help other people experiment how to accept payments by using bitcoind  / lnd / rtl 
in their own websites. The fortune cookie app was the simplest app that I could think of.
I have test server running on fortune.ranchokalan.com

**Comment by awb99** [comment]
When I go to Forwarding then I am seeing an error. I assume it is because I haven't yet connected
peers to my LNC server. Not sure.

```
Console: 
Switch: 14: 1553860786205: INFO: Switch Post Options: {"url":"http://localhost:8089/v1/switch","rejectUnauthorized":false,"json":true,"headers":{"Grpc-Metadata-macaroon":"0201036c6e6402cf01030a106be879eb290cfa4655be047652ebb7251201301a160a0761646472657373120472656164120577726974651a130a04696e666f120472656164120577726974651a170a08696e766f69636573120472656164120577726974651a160a076d657373616765120472656164120577726974651a170a086f6666636861696e120472656164120577726974651a160a076f6e636861696e120472656164120577726974651a140a057065657273120472656164120577726974651a120a067369676e6572120867656e65726174650000062072948457c0ce718433df37dbbdbfdf4151f8b7d0a296b155fde77dae115f467c"},"form":"{}"}
Console: 
Switch: 28: 1553860786207: ERROR: Switch Post Error: {"name":"RequestError","message":"Error: connect ECONNREFUSED 127.0.0.1:8089","cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8089},"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8089},"options":{"url":"http://localhost:8089/v1/switch","rejectUnauthorized":false,"json":true,"headers":{"Grpc-Metadata-macaroon":"0201036c6e6402cf01030a106be879eb290cfa4655be047652ebb7251201301a160a0761646472657373120472656164120577726974651a130a04696e666f120472656164120577726974651a170a08696e766f69636573120472656164120577726974651a160a076d657373616765120472656164120577726974651a170a086f6666636861696e120472656164120577726974651a160a076f6e636861696e120472656164120577726974651a140a057065657273120472656164120577726974651a120a067369676e6572120867656e65726174650000062072948457c0ce718433df37dbbdbfdf4151f8b7d0a296b155fde77dae115f467c"},"form":"{}","method":"POST","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
```

**Comment by ShahanaFarooqui** [comment]
@awb99 RTL should be able to read 'enableLogging' under Settings header, but currently it is not working. It will be fixed with our next release. Till then, please add 'enableLogging=true' under [Authentication] header. RTL will then generate /logs/RTL.log which you can share with us.

**Comment by saubyk** [comment]
@awb99

Can you please specify the lndServerUrl with https instead of http?

**Comment by ShahanaFarooqui** [comment]
@awb99 Please mask all the passwords, macaroon and other sensitive data before posting it.

**Comment by awb99** [comment]
I am running 4 docker images via docker-compose. I tried https but this
rejects the calls. To get valid certificates I guess I would need somehow
put a proxy with letsencrypt certificates in front of lnd. My idea is to
have a very easy test setup that works  within a few minutes after git
cloning it. So I am not sure if it ia a good idea to do that. And once I am
done with development the lnd server would only be accessible from the
other soxker images anyhow. So I dont think https is a good idea really.

**Comment by awb99** [comment]
@ShahanaFarooqui  Agreed, sensitive data should be masked. However the LND daemon re-genertes the macaroons on each startup, so the posted macaroons are already useless. hahha

**Comment by ShahanaFarooqui** [comment]
@awb99 Phew :p :) but it will still be better if macaroon path, rtlpass will also be masked. We do not want to take any risk with our users information, specially when you are running it on mainnet. :)

**Comment by saubyk** [comment]
@awb99 can you please check the BTCPayserver setup?
They are also serving lnd on http but its all behind nginx proxy.

Unless the tls encryption is somehow disabled for lnd, I am not sure if you will get an unencrypted response from lnd on http.

**Comment by awb99** [comment]
cat logs/RTL.log
```
Config Setup Variable PORT: 3000
Config Setup Variable LND_SERVER_URL: http://lnd:8089/v1
Config Setup Variable MACAROON_PATH: /lnd/data/chain/bitcoin/mainnet
Config Setup Variable NODE_AUTH_TYPE: CUSTOM
Config Setup Variable LND_CONFIG_PATH: 
Config Setup Variable RTL_CONFIG_PATH: /RTL
Config Setup Variable BITCOIND_CONFIG_PATH: 
Config Setup Variable RTL_SSO: 0
Config Setup Variable RTL_COOKIE_PATH: 
Config Setup Variable LOGOUT_REDIRECT_LINK: /login
Conf: 7: 1553863957728: INFO: Getting RTL Config
Calling getinfo from lnd server url: INFO: http://lnd:8089/v1/getinfo
Switch: 14: 1553864000516: INFO: Switch Post Options: {"url":"http://lnd:8089/v1/switch","rejectUnauthorized":false,"json":true,"headers":{"Grpc-Metadata-macaroon":"0201036c6e6402cf01030a106be879eb290cfa4655be047652ebb7251201301a160a0761646472657373120472656164120577726974651a130a04696e666f120472656164120577726974651a170a08696e766f69636573120472656164120577726974651a160a076d657373616765120472656164120577726974651a170a086f6666636861696e120472656164120577726974651a160a076f6e636861696e120472656164120577726974651a140a057065657273120472656164120577726974651a120a067369676e6572120867656e65726174650000062072948457c0ce718433df37dbbdbfdf4151f8b7d0a296b155fde77dae115f467c"},"form":"{}"}
Switch: 28: 1553864000521: ERROR: Switch Post Error: {"name":"RequestError","message":"Error: Parse Error","cause":{"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"},"error":{"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"},"options":{"url":"http://lnd:8089/v1/switch","rejectUnauthorized":false,"json":true,"headers":{"Grpc-Metadata-macaroon":"0201036c6e6402cf01030a106be879eb290cfa4655be047652ebb7251201301a160a0761646472657373120472656164120577726974651a130a04696e666f120472656164120577726974651a170a08696e766f69636573120472656164120577726974651a160a076d657373616765120472656164120577726974651a170a086f6666636861696e120472656164120577726974651a160a076f6e636861696e120472656164120577726974651a140a057065657273120472656164120577726974651a120a067369676e6572120867656e65726174650000062072948457c0ce718433df37dbbdbfdf4151f8b7d0a296b155fde77dae115f467c"},"form":"{}","method":"POST","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}/RTL # 
```

**Comment by awb99** [comment]
I have now re-written my docker-compose to be pretty much identical to the one from BTCPayServer

```
 rtl:
        image: rtl
        container_name: rtl
        build:
          context: rtl/
        environment:
          LND_SERVER_URL: http://lnd:8089/v1
          MACAROON_PATH: /lnd/data/chain/bitcoin/mainnet
          LND_CONFIG_PATH: /RTL/lnd.conf
          RTL_CONFIG_PATH: /RTL/RTL.conf
          BITCOIND_CONFIG_PATH: /bitcoind/bitcoin.conf
          RTL_SSO: 1
          RTL_COOKIE_PATH: /RTL/.cookie
          LOGOUT_REDIRECT_LINK: /server/services
        volumes:
            - lnd:/lnd
            - rtl:/rtldata
            - bitcoind:/bitcoind
        # HOST:CONTAINER
        ports:
           - "3000:3000"
        links:
          - "lnd:lnd"
        depends_on:
          - lnd
        entrypoint: ["./start-rtl.sh"]
```

It passes an environment variable RTL_CONFIG_PATH: /RTL/RTL.conf
Now it happens that the RTL.conf is completely ignored. 
I "telneted" into the RTL docker image, and the environment variable is there, but
it does not load the RTL.conf at all. When it starts up it wants to load the RTL.conf from
"/RTL" and somehow strips off the RTL.conf filename. Is this expected behavior?

**Comment by ShahanaFarooqui** [comment]
@awb99 We are not experts in docker and will not be of much help on that. 

But here are some suggestions on your environment settings:

1: If the server will not find any value for RTL_CONFIG_PATH then it will search RTL.conf in the root folder automatically. So, you can try to remove 'RTL_CONFIG_PATH' from your image.

2: Also, RTL_SSO should set to be 0, if you are not running node rtl server (port 3000) on https. otherwise authentication will fail. So, you can try to change RTL_SSO to 0 and set nodeAuthType=CUSTOM & rtlPass='your-custom-password' in RTL.conf.

3: LND_CONFIG_PATH value is required only if you want to authenticate through your lnd.conf's bitcoind.rpcpass value. So, you can remove this variable if you are ok to authenticate with CUSTOM type described under point 2. If not, then please specify the correct 'LND_CONFIG_PATH', as lnd.conf should not be in RTL root.

**Comment by saubyk** [comment]
@awb99 closing this ticket.
Hope your issue is addressed now.
Feel free to open a new one, in case you face any other problems. Thanks.
