### ISSUE TITLE
Unable to add Peers w/ .onion addresses

### ISSUE THREAD

**Issue by Amacruz** [ShahanaFarooqui/RTL#96]
**Describe the bug**
Don't know if this is a bug or a feature request... When I try to add any peers with TOR node address (.onion), I get an error and cannot connect.

**To Reproduce**
1. Go to 'Peers'
2. Paste node address with .onion in 'Add Peer'
3. Select 'Add'
4. Get Node Address Failed
    Code:500
    Message:Not Found\n

**Expected behavior**
Peer Added.

**Actual behavior**
Get eror

**Screenshots**

**Your environment**
* Latest version of BTCPayServer
* operating system (Ubuntu 18)

**Additional context**

**Comment by saubyk** [comment]
Hi @Amacruz
This should be addressed at LND level.
RTL is just returning you the error, which LND API threw.

RTL is just providing you a UI layer to work with LND, via its APIs.

LND needs to provide a better way to connect with nodes running on TOR.

Current option is that the, TOR node connects first with the public node, and then the public node can open back a channel.

**Comment by ShahanaFarooqui** [comment]
@Amacruz Closing the issue as it is not related to RTL.

**Comment by Amacruz** [comment]
HI saubyk,

Thanks for the prompt response.! I guess I'll have to wait until LND codes a better way to deal with TOR and deal with the workaround.

Thanks again! Have a good weekend!
