### ISSUE TITLE
Show non-zero block hash

### ISSUE THREAD

**Issue by MaxHillebrand** [ShahanaFarooqui/RTL#99]
**Describe the feature request**
This is a minor GUI feature request of the `LND Wallet / List Transactions` window. Currently, it shows the block hash, but starting from the very beginning, thus it only shows zeros, regardless which block it actually is.

**Describe the solution you'd like**
Show the block hash of the block, but starting with the first non-zero value.
For example:
`269804cd624d2755e3cf24c61c8e0bcd5b441921063059`
and not
`000000000000000000269804cd624d2755e3cf24c61c8e0bcd5b441921063059`.

**Screenshot of current implementation**
![image](https://user-images.githubusercontent.com/30683012/55278179-3de8f880-5309-11e9-8e70-b9a8b0c4d0c2.png)

**Comment by saubyk** [comment]
Thanks @MaxHillebrand makes sense. Can include for the next release.

**Comment by ShahanaFarooqui** [comment]
Done.
